/**
 * 变异清单——**每一道闸一条**。
 *
 * 这一层要回答的问题不是「闸门写了吗」，是「闸门**在挡**吗」。两者的区别在
 * diff 里看不出来：一个被注释掉的判断、一个永远为假的条件、一个 return 提前了
 * 三行，看起来都像正常代码。唯一能分辨的办法是**把它拆掉，看测试红不红**。
 *
 * ## 为什么是源码级替换，不是 `MAST_MUTATE=<gate>` 环境变量
 *
 * PLAN §8.4 原本写的是运行期开关。做到一半意识到那意味着**发布出去的代码里带着
 * 一个能关掉安全闸的环境变量**——而这台仪器上「设一次调试用、然后忘了取消」
 * 是完全现实的事。TS 不做基于 env 的死代码消除，插件是以 JS 形态装进 profile 的，
 * 所以那个开关会一直活在真机的运行时里。
 *
 * 源码级替换给的保证一模一样（三判据全在），而**生产代码一个字都不变**。
 * 代价是每条变异要重新构建一次，慢。慢是可以接受的：这套东西一天跑一次，
 * 而那个环境变量要在真机上活一辈子。
 *
 * ## 三判据（缺一条，「没变红」和「压根没验」就长得一模一样）
 *
 * 1. **变异落地**：替换串在文件里唯一命中，且改完能 grep 到新串；
 * 2. **构建通过**：`tsc -b` 退出码为 0 —— 编译不过的变异不算数；
 * 3. **测试确实跑了**，且**跑的范围包含被变异的文件** —— 这一条是 2.12 当场撞出来的，
 *    脚本当时写死了只跑 kernel，而变异在另一个包里，于是两条演练「绿」得毫无意义。
 */
export interface Mutation {
  /** 稳定 id，报告与 CI 都按它索引。 */
  readonly id: string
  /** 这道闸挡的是什么。拆掉它，系统就会重新犯哪一次错。 */
  readonly why: string
  readonly file: string
  /** 必须在文件里**唯一**命中。 */
  readonly find: string
  readonly replace: string
  /** 跑哪一批测试。必须覆盖 `file`。 */
  readonly scope: string
}

const K = 'packages/host/kernel/src'
const R = 'packages/host/stm-records/src'
const SK = 'packages/host/stm-skills/src'
const SF = 'packages/host/stm-safety/src'
const NF = 'packages/host/nanonis-files/src'
const NU = 'packages/host/numerics/src'

export const MUTATIONS: readonly Mutation[] = [
  // ── 内核的闸 ────────────────────────────────────────────────────────
  {
    id: 'k2-abort-latch',
    why: '中止闩：人喊了停之后，除退针与停扫外一切都该被拒。拆掉 ⇒ 喊停无效',
    file: `${K}/skill-kernel.ts`,
    find: "    if (this.deps.abortLatched?.() === true) {",
    replace: "    if (false && this.deps.abortLatched?.() === true) {",
    scope: 'packages/host',
  },
  {
    id: 'k3-sample-gate',
    why: '样品闸：产数据的操作必须有归属样品。拆掉 ⇒ 以后没人能定位这条记录测的是什么',
    file: `${K}/skill-kernel.ts`,
    find: '      const gate = this.deps.sampleGate?.(spec) ?? null',
    replace: '      const gate = ((): string | null => (void this.deps.sampleGate, null))()',
    scope: 'packages/host',
  },
  {
    id: 'k6-required',
    why: '必填检查：省略 required 即必填。拆掉 ⇒ 广告成必填却不强制，模型漏传时到技能里才炸',
    file: `${K}/skill-kernel.ts`,
    find: '      if ((p.required ?? true) && !has) {',
    replace: '      if (p.required === true && !has) {',
    scope: 'packages/host',
  },
  {
    id: 'k7-safety-gate',
    why: '安全闸：荒谬值 / 包络 / 模式 / 硬闸的总入口。拆掉 ⇒ 四类拦截同时失效',
    file: `${K}/skill-kernel.ts`,
    find: '    const refusal = this.deps.safetyGate?.(spec, params) ?? null',
    replace: '    const refusal = ((): string | null => (void this.deps.safetyGate, null))()',
    scope: 'packages/host',
  },
  {
    id: 'k16-record-every-outcome',
    why: '记录每一个结局：被拒的调用也记。拆掉 ⇒ 回到「为什么什么都没发生」无从回答的状态',
    file: `${K}/skill-kernel.ts`,
    find: '        this.deps.record?.({',
    replace: "        if (o.kind === 'ok') this.deps.record?.({",
    scope: 'packages/host',
  },
  {
    id: 'k16-record-parsed-params',
    why: '记解析后的参数。拆掉 ⇒ schema 那四个生成列全 NULL，按数值查历史直接问不出来',
    file: `${K}/skill-kernel.ts`,
    find: '      recorded = params',
    replace: '      void params',
    scope: 'packages/host',
  },

  // ── 安全判据 ────────────────────────────────────────────────────────
  {
    id: 'safety-physically-absurd',
    why: '物理荒谬：11 条「这个数在这台仪器上不可能是本意」。拆掉 ⇒ 1.5 A 这类值一路放行',
    file: `${K}/safety.ts`,
    find: 'export function physicallyAbsurdViolations(',
    // 改名会连带打断测试文件的 import（构建失败 ⇒ 判 inconclusive，不算数）。
    // 所以留下同名同签名的空壳，把真身改名藏起来。
    replace: `export function physicallyAbsurdViolations(...__a: unknown[]): string[] {
  void __a
  return []
}
void physicallyAbsurdViolations_unused
function physicallyAbsurdViolations_unused(`,
    scope: 'packages/host',
  },
  {
    id: 'schema-effective-bounds',
    why: '广告与执行同源：界要与安全包络求交。拆掉 ⇒ 2026-08-10 的 16 个米制参数重现',
    file: `${K}/tool-schema.ts`,
    find: `  if (gLo !== null) lo = lo === null ? gLo : Math.max(lo, gLo)
  if (gHi !== null) hi = hi === null ? gHi : Math.min(hi, gHi)`,
    replace: `  void gLo
  void gHi`,
    scope: 'packages/host',
  },
  {
    id: 'schema-enum-skips-si',
    why: '枚举不走 SI 解析。拆掉 ⇒ 内核拿 "low" 去 parseQuantity，拒掉一次完全合法的调用',
    file: `${K}/tool-schema.ts`,
    find: '    if (p.allowedValues !== undefined && p.allowedValues.length > 0) continue',
    replace: '    void p.allowedValues',
    scope: 'packages/host',
  },

  // ── dsh 接缝 ────────────────────────────────────────────────────────
  {
    id: 'tool-bounds-into-description',
    why: 'D-SCHEMA-2：dsh 收不下数值界，只能折进描述。拆掉 ⇒ 模型再也读不到范围',
    file: `${SK}/tool.ts`,
    find: '    const sentence = boundsSentence(prop.minimum, prop.maximum)',
    replace: `    void boundsSentence
    const sentence = ''`,
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'tool-validation-teaching-text',
    why: 'D-SCHEMA-3：参数校验失败要贴回教学文案。拆掉 ⇒ 模型只读到英文样板，改不动',
    file: `${SK}/tool.ts`,
    find: "      if (result.error.info?.code !== 'INVALID_ARGS') return undefined",
    replace: "      if (result.error.info?.code !== 'NEVER_HAPPENS') return undefined",
    scope: 'packages/host/stm-skills',
  },

  // ── 记录层 ──────────────────────────────────────────────────────────
  {
    id: 'rec-unscoped-sentinel',
    why: 'D-REC-1：没有实验时也记。拆掉 ⇒ 样品闸的拒绝一条都留不下',
    file: `${R}/store.ts`,
    find: '          input.experimentId ?? UNSCOPED,',
    replace: "          input.experimentId ?? '不存在的实验',",
    scope: 'packages/host/stm-records',
  },
  {
    id: 'rec-approval-row',
    why: 'D-REC-2：人批准的要写 approvals。拆掉 ⇒ 空表和「没人准过」又长得一样了',
    file: `${R}/store.ts`,
    find: "        ? ['human_operator', 'gui_click']",
    replace: "        ? ['automated_policy', 'gui_click']",
    scope: 'packages/host/stm-records',
  },
  {
    id: 'rec-status-rolled-back',
    why: 'rolled_back 是独立状态。拆掉 ⇒ 回滚过的动作和普通失败分不开',
    file: `${R}/store.ts`,
    find: `  if (kind === 'ok') return 'succeeded'
  if (kind === 'rolled_back') return 'rolled_back'
  return 'failed'`,
    replace: "  return kind === 'ok' ? 'succeeded' : 'failed'",
    scope: 'packages/host/stm-records',
  },
  {
    id: 'ledger-success-only-artifacts',
    why: '只有成功的调用能贡献产物。拆掉 ⇒ 失败技能「本该写出」的路径去佐证声明',
    file: `${R}/ledger.ts`,
    find: '      if (success) {',
    replace: '      if (success || true) {',
    scope: 'packages/host/stm-records',
  },
  {
    id: 'ledger-absent-is-undefined',
    why: '没这一轮返回 undefined，不是空条目。拆掉 ⇒ 「不知道」被当成「没发生」，审计开始乱叫',
    file: `${R}/ledger.ts`,
    find: '    return e === undefined ? undefined : { skills: [...e.skills], artifacts: [...e.artifacts] }',
    replace:
      '    return e === undefined ? { skills: [], artifacts: [] } : { skills: [...e.skills], artifacts: [...e.artifacts] }',
    scope: 'packages/host/stm-records',
  },
  {
    id: 'audit-windows-path-semantics',
    why: 'D-REC-4：路径比较写死 Windows。拆掉 ⇒ 同一条判据在开发机与 CI 上给两个答案',
    file: `${R}/claim-audit.ts`,
    find: "  const parts = p.replace(/\\//g, '\\\\').split('\\\\')",
    replace: "  const parts = p.split('\\\\')",
    scope: 'packages/host/stm-records',
  },
  // ── 批 1/2 的技能闸 ──────────────────────────────────────────────────
  {
    id: 'park-undeclared-before-missing',
    why: '没声明符号排在读不到之前。拆掉 ⇒ 一个「白等」被报成「再等等」，轮询耗光预算才收工',
    file: `${K}/tip-park.ts`,
    find: "  if (undeclared.length > 0) {",
    replace: "  if (undeclared.length > 0 && missing.length === 0) {",
    scope: 'packages/host',
  },
  {
    id: 'park-rail-side-by-sign',
    why: '收回端由 z_extend_sign 定。拆掉 ⇒ 把顶在伸长端(朝样品那侧)的针判成已退针',
    file: `${K}/tip-park.ts`,
    find: `      ? ([travel.lo_m, 'low', travel.hi_m] as const)
      : ([travel.hi_m, 'high', travel.lo_m] as const)`,
    replace: `      ? ([travel.hi_m, 'high', travel.lo_m] as const)
      : ([travel.lo_m, 'low', travel.hi_m] as const)`,
    scope: 'packages/host',
  },
  {
    id: 'park-soft-limits-need-enabled',
    why: '软限只有启用时才算数。拆掉 ⇒ 拿一对惰性数字当边界，Z 顶死时告警不会响',
    file: `${K}/tip-park.ts`,
    find: '  if (opts.zLimitsEnabled === true && opts.zLimitsM != null) {',
    replace: '  if (opts.zLimitsEnabled !== false && opts.zLimitsM != null) {',
    scope: 'packages/host',
  },
  {
    id: 'park-is-parked-only-parked',
    why: '`isParked` 只在确认到位时为真。拆掉 ⇒ `unreadable` 被当成已退针',
    file: `${K}/tip-park.ts`,
    find: "  return v.state === PARKED",
    replace: "  return v.state !== NOT_PARKED",
    scope: 'packages/host',
  },
  {
    id: 'retract-retry-useful-exit',
    why: '配置缺口时立刻收工。拆掉 ⇒ 「白等」被报成「超时」，人会去调大预算而不是去填符号',
    file: `${SK}/l0/safe-retract.ts`,
    find: '        if (!retryUseful(verdict)) break',
    replace: '        void retryUseful',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'engage-fail-closed-no-current',
    why: '测不出隧穿就不建议粗进针。拆掉 ⇒ 测量链自己坏了成了盲目粗进针的触发条件',
    file: `${SK}/l0/engage.ts`,
    find: '    if (nValid === 0 || setpointA <= 0) {',
    replace: '    if (false && (nValid === 0 || setpointA <= 0)) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'engage-fail-closed-loop-open',
    why: '确认不了反馈环已开就不建议粗进针。拆掉 ⇒ 带着闭合的环把粗动马达开进表面',
    file: `${SK}/l0/engage.ts`,
    find: '    if (!(v.verified && v.on === false)) {',
    replace: '    if (!(v.verified || v.on === false)) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'move-stall-counter',
    why: '连续逐位不变 ⇒ 停住了。拆掉 ⇒ 「夹住」被说成「可能仍在移动中」，外环去等一个不会发生的事',
    file: `${SK}/l0/move.ts`,
    find: '    const stalled = frozen >= STALL_POLLS',
    replace: '    const stalled = frozen >= STALL_POLLS && false',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'gated-call-abort-verbs',
    why: '动词级中止门。拆掉 ⇒ 中止落在技能中段时，它自己的退针会被自己触发的闸拒掉 —— 人按了中止，针留在原地',
    file: `${SK}/gated-call.ts`,
    find: '    if (isAbortSafe(method, args)) return opts.call(method, ...args)',
    replace: '    void isAbortSafe',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'k2-abort-reason-honesty',
    why: '没原因时不假定是人停的。拆掉 ⇒ 人去翻自己的操作记录，而真正的原因在服务日志的 CRITICAL 行里',
    file: `${K}/skill-kernel.ts`,
    find: "          : '**没有留下中止原因** —— 别假定是人停的:急停、E_STOP 事件、' +",
    replace: "          : '用户已中止本次运行。' + '' +",
    scope: 'packages/host',
  },
  // ── 组合执行器的四条恢复守卫（四次真机事故的现场）────────────────────
  {
    id: 'graph-terminal-guard',
    why: '跑完了的既往进度不许当断点续跑。拆掉 ⇒ 整个计划被跳过，而外面看到的是一次数字完全正常的成功（2026-07-10 假进针 / 2026-07-27 五个 region 0.37 秒「扫完」）',
    file: `${K}/graph-executor.ts`,
    find: '  return total > 0 && done >= total',
    replace: '  return total > 0 && done >= total && false',
    scope: 'packages/host',
  },
  {
    id: 'graph-drop-stale-abort',
    why: '恢复时丢掉上一次的中止。拆掉 ⇒ 「重试」静默变成「重放」：回包用时 0.0 分钟、error 一字不差还是上一轮那句（2026-08-23）',
    file: `${K}/graph-executor.ts`,
    find: '  p.aborted = false',
    replace: '  p.aborted = true',
    scope: 'packages/host',
  },
  {
    id: 'graph-clear-completed-sidecar',
    why: '跑完删掉自己的断点。拆掉 ⇒ 同一次运行里的下一次调用捡到它，跳掉每一步（2026-08-12 ForgeAuTip 的 finalize 被跳过，这个失败模式的第三次出货）',
    file: `${K}/graph-executor.ts`,
    find: '      this.#clearSidecar()',
    replace: '      void this.#clearSidecar',
    scope: 'packages/host',
  },
  {
    id: 'graph-abort-before-step',
    why: '每一步之前查中止闩。拆掉 ⇒ 人按着中止，计划照样一步步走完',
    file: `${K}/graph-executor.ts`,
    find: '      if (this.#checkAbort()) {',
    replace: '      if (false && this.#checkAbort()) {',
    scope: 'packages/host',
  },
  {
    id: 'graph-halt-must-be-a-reason',
    why: '停机必须是一个字符串理由。拆掉 ⇒ 一个返回真值哨兵的桩上下文把每个计划都停在第一步',
    file: `${K}/graph-executor.ts`,
    find: "    return typeof reason === 'string' ? reason : ''",
    replace: '    return String(reason ?? "")',
    scope: 'packages/host',
  },
  {
    id: 'graph-abort-facts-operator-only',
    why: '只有中止闩才算「人喊停」。拆掉 ⇒ 一次 CRITICAL 停机被报成「你中止了」，而人从没碰过它（2026-07-28 #46，连报三次）',
    file: `${K}/graph-executor.ts`,
    find: '    aborted && (!reason || reason === ABORT_LATCH_REASON || reason === USER_ABORT_TEXT)',
    replace: '    aborted && reason.length >= 0',
    scope: 'packages/host',
  },
  // ── 等扫描：三条真机事故各一条 ────────────────────────────────────────
  {
    id: 'wait-lines-mismatch-refusal',
    why: '帧行数与缓冲区配置对不上就拒绝判断。拆掉 ⇒ 两个描述不同对象的数相除，**制造**出一个截断',
    file: `${K}/scan-wait.ts`,
    find: '  if (configured !== null && rows !== configured) return { ...UNMEASURED, linesTotal: configured }',
    replace: '  void 0',
    scope: 'packages/host',
  },
  {
    id: 'wait-never-started',
    why: '一次都没见它跑 + 缓冲区确证 0 行 ⇒ 它从没开始。拆掉 ⇒ 一次刚发起的扫描被判成「中途停止 (0/256 行)」，报错还把人指向去查是谁停的（2026-08-13，0.31 秒）',
    file: `${K}/scan-wait.ts`,
    find: '  const neverStarted = !seenRunning && lines.linesDone === 0',
    replace: '  const neverStarted = false && !seenRunning && lines.linesDone === 0',
    scope: 'packages/host',
  },
  {
    id: 'wait-extension-needs-progress',
    why: '延期要靠行数严格增长挣到。拆掉 ⇒ 一次冻在第 300 行的扫描照样续命，而一台读不出缓冲区的机器在每次超时上永远等下去',
    file: `${K}/scan-wait.ts`,
    find: '  if (prev === null || done <= prev) return no(false, done)',
    replace: '  void done',
    scope: 'packages/host',
  },
  {
    id: 'wait-frame-restarted',
    why: '行数掉下去是换帧，不是卡住。拆掉 ⇒ 把一次 Continuous scan 叫「卡住」，下一个读的人去找一个卡住的压电（2026-08-09 实测 234 → 208 行）',
    file: `${K}/scan-wait.ts`,
    find: '  if (prev !== null && done < prev) return no(true, done)',
    replace: '  if (prev !== null && done < prev) return no(false, done)',
    scope: 'packages/host',
  },
  {
    id: 'wait-stop-scan-on-abort',
    why: '中止时先停扫再返回。拆掉 ⇒ 人按了中止，扫描还在跑 —— 仪器被留在运动中',
    file: `${SK}/composite/wait-scan-complete.ts`,
    find: '    if (aborted) await this.#stopScan()',
    replace: '    void aborted',
    scope: 'packages/host/stm-skills',
  },
  // ── 偏压斜坡：假起点 ────────────────────────────────────────────────
  {
    id: 'ramp-no-fake-start',
    why: '读不到当前偏压就拒绝。拆掉 ⇒ 真实偏压 1 V 而起点被当成 0，第一步把硬件从 1 V 拽到近 0 —— 正是 slew 存在的意义所要防的突变',
    file: `${SK}/composite/set-bias-ramp.ts`,
    find: '    if (v === null) return { success: false, error: NO_START_BIAS_ERROR }',
    replace: '    if (v === null) return { success: true, data: { bias_v_start: 0 } }',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'ramp-endpoint-exact',
    why: 'linspace 的末位直接赋成 stop。拆掉 ⇒ 斜坡的终点差一个 ulp，而那是真的下发给硬件的电压',
    file: `${K}/bias-ramp.ts`,
    find: '  out[num - 1] = stop',
    replace: '  void stop',
    scope: 'packages/host',
  },
  // ── 进针判定：五次真机事故各一条 ──────────────────────────────────────
  {
    id: 'engage-noise-floor',
    why: '噪声底封住「调低电流假装进针」。拆掉 ⇒ 把设定点调到 1 fA，放大器噪声就「达到」了它（#75 原话：调低电流假装进到针了）',
    file: `${K}/engage.ts`,
    find: '  return Math.max(0.5 * Math.abs(setpointA), MIN_ENGAGED_CURRENT_A)',
    replace: '  return 0.5 * Math.abs(setpointA)',
    scope: 'packages/host',
  },
  {
    id: 'engage-bar-needs-setpoint',
    why: '设定点读不到或为 0 ⇒ 算不出判据线就不许判。拆掉 ⇒ 一个读不到设定点的装机会拿 0 当线，任何噪声都「过线」',
    file: `${K}/engage.ts`,
    find: '  if (setpointA === null || setpointA === undefined || setpointA === 0) return null',
    replace: '  if (setpointA === null || setpointA === undefined) return null',
    scope: 'packages/host',
  },
  {
    id: 'engage-two-agreeing-reads',
    why: '两次一致才下结论。拆掉 ⇒ 单次读数说了算，而模块停下那一刻正是电流唯一保证在途中的时刻——2026-08-05 一次成功的进针就是这么被判成失败的',
    file: `${K}/engage.ts`,
    find: '      if (run >= agreeN) {',
    replace: '      if (run >= 1) {',
    scope: 'packages/host',
  },
  {
    id: 'engage-unreadable-breaks-run',
    why: '读不到会打断连续计数。拆掉 ⇒ 一次没读到被当成「上一次仍然成立」，于是一个读数加一次失败凑成了「两次一致」',
    file: `${K}/engage.ts`,
    find: '      ;[runSide, run] = [null, 0]',
    replace: '      ;[runSide, run] = [runSide, run]',
    scope: 'packages/host',
  },
  {
    id: 'engage-unknown-is-not-zero',
    why: '判不出时 engaged 保持 null。拆掉 ⇒ 「没测出来」被报成「测出来是零」，那正是把人支去看电机量程的那句话',
    file: `${K}/engage.ts`,
    find: "  if (v.engaged === null) {",
    replace: "  if (false && v.engaged === null) {",
    scope: 'packages/host',
  },
  {
    id: 'engage-parse-running-unreadable',
    why: '状态位读不懂 ⇒ null，不是「没在跑」。拆掉 ⇒ 一次解析故障答出一个具体的仪器状态（这个位置已经在真机上静默报过一次「未在运行」）',
    file: `${K}/engage.ts`,
    find: '    if (inner.length === 0) return null',
    replace: '    if (inner.length === 0) return false',
    scope: 'packages/host',
  },
  {
    id: 'engage-z-travel-is-evidence',
    why: 'Z 纹丝不动与 Z 在推进是两句话。拆掉 ⇒ 一趟只是 4 K 下步长太短的健康进针被说成「卡住」，而下一步该做什么完全取决于是哪一件（2026-08-08 整晚查一个不存在的秒停）',
    file: `${K}/engage.ts`,
    find: '    if (this.zTravelM <= 0) {',
    replace: '    if (false) {',
    scope: 'packages/host',
  },
  {
    id: 'approach-confirm-stopped',
    why: '读到「停了」要复读一次。拆掉 ⇒ 一次瞬态读数掐掉一趟正在走的进针，而症状和「模块自己停了」一模一样',
    file: `${SK}/composite/auto-approach.ts`,
    find: '        if (observedRunning && !(await this.#confirmStopped(progress))) {',
    replace: '        if (false && observedRunning && !(await this.#confirmStopped(progress))) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'approach-stop-on-abort',
    why: '中止时先停模块再返回。拆掉 ⇒ 人按了中止，进针模块还在把针尖往表面压',
    file: `${SK}/composite/auto-approach.ts`,
    find: '        await this.#stopModule()',
    replace: '        void 0',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'approach-stop-failure-is-visible',
    why: '停机没下发必须留痕。拆掉 ⇒ 调用方拿到的东西和停成功时一模一样，它只会报「进针失败」，一个字不提「而且模块可能还在走」（2026-08-10）',
    file: `${SK}/composite/auto-approach.ts`,
    find: "    if (failed(rec)) this.#stopFailures.push(`AutoApproach_OnOffSet(0): ${rec.error}`)",
    replace: '    void rec',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'approach-timeout-not-success',
    why: '到上限还在跑不许报成功。拆掉 ⇒ 一趟没走到表面的进针被当成进到了，下一步是配扫描',
    file: `${SK}/composite/auto-approach.ts`,
    find: '      if (elapsed >= this.#timeoutS) return this.#afterTimeout(progress)',
    replace: '      if (false && elapsed >= this.#timeoutS) return this.#afterTimeout(progress)',
    scope: 'packages/host/stm-skills',
  },
  // ── 逃逸闸与 L2 分派 ─────────────────────────────────────────────────
  {
    id: 'refusal-clear-is-chain-scoped',
    why: '另一条链清不掉本链记的拒绝。拆掉 ⇒ 私聊里一次成功 engage 抹掉群聊十秒前记下的拒绝，2026-07-27 那道侧门重新打开',
    file: `${K}/approach-refusal.ts`,
    find: "    if (owner !== null && owner !== undefined && cur.owner !== '' && cur.owner !== owner) {",
    replace: "    if (owner === '\u0000never') {",
    scope: 'packages/host',
  },
  {
    id: 'refusal-expires',
    why: '拒绝到期自动失效。拆掉 ⇒ 一条没人再回头看的拒绝活得比它描述的硬件状态更久，粗进针从此调不动',
    file: `${K}/approach-refusal.ts`,
    find: '    if (this.ageS(r) >= r.ttlS) {',
    replace: '    if (false) {',
    scope: 'packages/host',
  },
  {
    id: 'refusal-gate-denies',
    why: '安全闸读到活着的拒绝就拒。拆掉 ⇒ 记下的拒绝谁都挡不住，整条闸等于没有',
    file: `${SF}/plugin.ts`,
    find: '    return isApproachEscalation(toolName) ? this.approachLatch.active() : null',
    replace: '    return isApproachEscalation(toolName) ? null : null',
    scope: 'packages/host/stm-safety',
  },
  {
    id: 'tip-records-refusal-on-engage-fail',
    why: 'engage 相失败要记一次拒绝。拆掉 ⇒ 正门拒了，侧门（直接 AutoApproach）却是开的',
    file: `${SK}/composite/approach-tip.ts`,
    find: `      const err = \`engage phase failed: \${eng.error ?? 'unknown'}\``,
    replace: `      const err = 'engage phase failed'; void this.#latch`,
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'tip-no-approach-on-a-maybe',
    why: 'engage 既没进针也没说要粗进针 ⇒ 停下。拆掉 ⇒ 在两个自相矛盾的判据上开一次粗进针',
    file: `${SK}/composite/approach-tip.ts`,
    find: "    if (engData['needs_auto_approach'] !== true) {",
    replace: "    if (false && engData['needs_auto_approach'] !== true) {",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'tip-verifies-after-approach',
    why: '粗进针跑完要自己再测一次。拆掉 ⇒ 一次过期续跑让 AutoApproach 报成功，0.17 pA 对 500 pA 也「确认」了进针（#42/#75）',
    file: `${SK}/composite/approach-tip.ts`,
    find: '    if (v.engaged !== true) {',
    replace: '    if (false && v.engaged !== true) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'kernel-composition-depth-cap',
    why: '组合嵌套上限。拆掉 ⇒ 一个自己调自己的技能把进程转死，而那时仪器还握在手里',
    file: `${K}/skill-kernel.ts`,
    find: '    if (depth + 1 >= MAX_COMPOSITION_DEPTH) {',
    replace: '    if (false) {',
    scope: 'packages/host',
  },
  // ── 扫描主链的判定件 ────────────────────────────────────────────────
  {
    id: 'tier-bound-tolerance',
    why: '上界带相对容差，边界值才真的落在小的那一档。拆掉 ⇒ 100 nm 从 highres 掉到 roi，速度悄悄变了（顺带查明：`<=` 与 `<` 在有容差时是等价的，真正承重的是容差）',
    file: `${K}/scan-policy.ts`,
    find: '    if (size <= tier.upperSizeM * (1 + BOUND_REL_TOL)) return tier',
    replace: '    if (size <= tier.upperSizeM * (1 - BOUND_REL_TOL)) return tier',
    scope: 'packages/host',
  },
  {
    id: 'line-time-explicit-must-be-positive',
    why: '显式给 0/负数要退回档位表。拆掉 ⇒ 一个 0 直接当线时间用，扫描速度算出来是 Infinity',
    file: `${K}/scan-policy.ts`,
    find: `    if (Number.isFinite(v) && v > 0) return { lineTimeS: v, source: 'explicit' }`,
    replace: `    if (Number.isFinite(v)) return { lineTimeS: v, source: 'explicit' }`,
    scope: 'packages/host',
  },
  {
    id: 'frame-extent-honours-angle',
    why: '包络必须算角度。拆掉 ⇒ 转 45° 的框对角线伸出 √2 倍却被算成没超，越界闸在转角帧上系统性失效',
    file: `${K}/scan-frame.ts`,
    find: '  const a = ((angleDeg ?? 0) * Math.PI) / 180',
    replace: '  const a = 0 * (angleDeg ?? 0)',
    scope: 'packages/host',
  },
  {
    id: 'frame-exceeds-needs-half-range',
    why: '半程读不到要返回 null（判不了）。拆掉 ⇒ 「读不到」被当成「没超」，那 15 % 不是数据的那一帧照常放行',
    file: `${K}/scan-frame.ts`,
    find: '  if (halfXM === null || halfXM === undefined || halfYM === null || halfYM === undefined) return null',
    replace: '  if (halfXM === null || halfXM === undefined || halfYM === null || halfYM === undefined) return { x: halfXM ?? Number.POSITIVE_INFINITY, y: halfYM ?? Number.POSITIVE_INFINITY }',
    scope: 'packages/host',
  },
  {
    id: 'frame-readback-unreadable-is-not-ok',
    why: '回读读不到 ⇒ unreadable，不是「对上了」。拆掉 ⇒ 仪器把框夹到量程内而上层完全看不出来，此后每张图的坐标都是假的',
    file: `${K}/scan-frame.ts`,
    find: '  if (readback === null || readback === undefined) return { unreadable: true }',
    replace: '  if (readback === null || readback === undefined) return null',
    scope: 'packages/host',
  },
  {
    id: 'match-signal-prefix-needs-boundary',
    why: '前缀匹配要带边界。拆掉 ⇒ 通道名 Z 撞上 Z-Controller，采的是另一路信号而没人报错',
    file: `${K}/scan-frame.ts`,
    find: "    if (nl.startsWith(ql) && (nl.length === ql.length || nl[ql.length] === ' ' || nl[ql.length] === '(')) {",
    replace: '    if (nl.startsWith(ql)) {',
    scope: 'packages/host',
  },
  {
    id: 'props-module-count-must-agree',
    why: '声明的个数与解出的数组不一致 ⇒ 未知，绝不修补。拆掉 ⇒ 一次错解被当成可信读数，写回一份残缺清单覆盖用户配的',
    file: `${K}/scan-reply.ts`,
    find: `  if (names.length !== count || !names.every((s) => typeof s === 'string')) return null`,
    replace: `  if (!names.every((s) => typeof s === 'string')) return null`,
    scope: 'packages/host',
  },
  {
    id: 'continuous-state-is-three-valued',
    why: 'GET 表只有 0/1，别的都是「不知道」。拆掉 ⇒ 一个 2（SET 侧的「关」）被读成「确认已关」，2026-08-19 那次就是这么答成一切正常的',
    file: `${K}/scan-reply.ts`,
    find: '  if (flag === GET_OFF) return false',
    replace: '  if (flag !== GET_ON) return false',
    scope: 'packages/host',
  },
  {
    id: 'configure-scan-refuses-unread-angle',
    why: '读不回当前角度就拒绝配帧。拆掉 ⇒ 用一个假定的 0° 静默把扫描框转正，而调用方要的是「保持当前角度」',
    file: `${SK}/l0/configure-scan.ts`,
    find: '      if (angle === null || !Number.isFinite(angle)) {',
    replace: '      if (angle === null && !(angle = 0, true)) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'configure-scan-frame-readback-gate',
    why: '写完读回来对不上就拒。拆掉 ⇒ 回声当读数，仪器夹过的框被当成设上了',
    file: `${SK}/l0/configure-scan.ts`,
    find: '  return frameReadbackMismatch(requested, readback)',
    replace: '  void requested; void readback; return null',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'configure-scan-piezo-range-gate',
    why: '框伸出压电量程就拒。拆掉 ⇒ 超出去那部分像素不是数据，而图看着完全正常（2026-08-28）',
    file: `${SK}/l0/configure-scan.ts`,
    find: '  return frameExceeds(cx, cy, w, h, angle, halfX, halfY)',
    replace: '  void [cx, cy, w, h, angle, halfX, halfY]; return null',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'start-scan-continuous-gate',
    why: '只有回读确认 continuous 关着才起扫。拆掉 ⇒ 一次 start 不再等于一帧，WaitScanComplete 只能等满超时而 SaveScan 拿到的可能是第 N+2 帧',
    file: `${SK}/l0/start-scan.ts`,
    find: `  if (i.stillOn === false) return ''`,
    replace: `  if (i.stillOn !== true) return ''`,
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'start-scan-props-need-read-list',
    why: '读不到模块清单就不下发 Scan_PropsSet。拆掉 ⇒ 一个空数组按「清空」语义把用户配好的清单抹掉',
    file: `${SK}/l0/start-scan.ts`,
    find: "    const propsWritten = moduleNamesSource === 'read' || moduleNamesSource === 'read_empty'",
    replace: '    const propsWritten = true',
    scope: 'packages/host/stm-skills',
  },
  // ── 抓帧落盘 / 找图 / 参数组 ────────────────────────────────────────
  {
    id: 'frame-must-keep-2d',
    why: '落盘的帧必须保住行列。拆掉 ⇒ 每个 .npy 都是扁的，断链断在测量之后一步：2026-07-28 那趟报告每个数都是真的，只是没有图',
    file: `${SK}/l0/frames.ts`,
    find: 'parseFrameGrab(body, true) ?? parseFrameGrab(body, false)',
    replace: 'parseFrameGrab(body, false)',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'frame-name-must-be-free',
    why: '取第一个空名。拆掉 ⇒ 同一毫秒里的第二发盖掉第一发（2026-07-28：下游拿上一趟的残留当本趟结果，而本趟落地时毁掉了上一趟）',
    file: `${SK}/l0/frames.ts`,
    find: '  while (existsSync(out)) {',
    replace: '  while (false && existsSync(out)) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'searched-dirs-must-exist',
    why: 'searched_dirs 只列真找过的目录。拆掉 ⇒ 报告一次没发生过的搜索，调用方据此断定「那儿没有图」',
    file: `${SK}/l0/frames.ts`,
    find: '      if (!statSync(real).isDirectory()) continue',
    replace: '      void statSync(real)',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'session-path-may-be-prefix',
    why: 'SessionPathGet 报的可能是「目录 + 文件名前缀」，要取上级。拆掉 ⇒ 存在 working-sessions 之外的图一律找不到（2026-06-29：path:null，而文件就在那儿）',
    file: `${SK}/l0/frames.ts`,
    find: '  const up = dirname(s)',
    replace: '  const up = s',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'preset-never-clamps',
    why: '超范围就拒，从不夹紧。拆掉 ⇒ 被悄悄改小的值会让你以为自己设的是原来那个数',
    file: `${K}/zctrl-preset.ts`,
    find: '  if (value >= lo && value <= hi) return',
    replace: '  if (true) return',
    scope: 'packages/host',
  },
  {
    id: 'preset-duplicate-needs-overwrite',
    why: '同名默认拒，覆盖要显式说。拆掉 ⇒ 一次手滑把用户调了一下午的那组参数换掉，而返回值看起来完全正常',
    file: `${K}/zctrl-preset.ts`,
    find: '    if (at >= 0 && !overwrite) {',
    replace: '    if (false && at >= 0 && !overwrite) {',
    scope: 'packages/host',
  },
  {
    id: 'npy-header-64-align',
    why: '.npy 头部要补到 64 字节的整数倍。拆掉 ⇒ 在 np.load 抛异常之前一切看起来都正常，而那时那一帧已经扫完了',
    file: `${K}/npy.ts`,
    find: '  const headerLen = dict.length + 1 + ((NPY_ALIGN - (unpadded % NPY_ALIGN)) % NPY_ALIGN)',
    replace: '  const headerLen = dict.length + 1 + (void unpadded, 0)',
    scope: 'packages/host',
  },
  {
    id: 'py-repr-exponent-band',
    why: 'Python 在 1e-4 换指数记法，JS 要到 1e-6。拆掉 ⇒ setpoint_a 的上界 1e-7 在超界报文里印成 JS 的写法，而那句话是模型读的',
    file: `${K}/si.ts`,
    find: '  if (decpt > -4 && decpt <= 16) {',
    replace: '  if (decpt > -6 && decpt <= 21) {',
    scope: 'packages/host',
  },
  // ── 写后回读 / 参数组的解析与放回 ──────────────────────────────────
  {
    id: 'readback-tolerance-is-load-bearing',
    // 变异打在**容差这个数**上而不是那个 `if` 上：把 `isClose(...)` 换成 `===`
    // 会让 `isClose` 变成未使用的函数、`tsc` 报错，于是那条变异永远编不过
    // （「一道闸如果拆不开试一次，它就没被验过」，本仓第四次）。
    // 而 relTol = 0 时 `isClose` 本来就退化成精确相等 —— 同一个缺陷，编得过。
    why: '写后回读比对留 1e-3 相对容差。归零 ⇒ 退化成精确相等，真机上每一次写增益都判「不一致」、回滚、并叫人别进针，而报文里写着「相差 1 倍」',
    file: `${K}/readback.ts`,
    find: 'export const READBACK_REL_TOL = 1e-3',
    replace: 'export const READBACK_REL_TOL = 0',
    scope: 'packages/host',
  },
  {
    id: 'readback-rejects-unreadable',
    // 这道闸原先写在 `valuesMatch` 的 `if` 里，下游的类型收窄挂在它身上 ⇒
    // 改成永远为假就编不过。提成 `bothNumbers` 之后它拆得开了
    // （同 `knownHalfRange` / `checkFrameReadback` 那条规则，本仓第四次）。
    why: '「读不到」不是「一样」。拆掉 ⇒ 一个 null 回读被当成「硬件收下了」，而那正是回读这件事要防的东西',
    file: `${K}/readback.ts`,
    find: '  return a === null || b === null ? null : [a, b]',
    replace: '  return [a as number, b as number]',
    scope: 'packages/host',
  },
  {
    id: 'preset-approach-needs-profile',
    why: '进针参数只由用户输入。拆掉 ⇒ 编一组「常见值」顶上，以本机标定的名义跑一次真实的进针',
    file: `${K}/zctrl-preset.ts`,
    find: '  if (missing.length > 0) {',
    replace: '  if (false && missing.length > 0) {',
    scope: 'packages/host',
  },
  {
    id: 'preset-scan-needs-frame-size',
    why: '读不到帧宽就拒，不挑一档。拆掉 ⇒ 用一组不对的增益扫一整帧，而没人知道它是怎么选中的',
    file: `${K}/zctrl-preset.ts`,
    find: '  return size === null || size === undefined || !Number.isFinite(size) ? null : size',
    replace: '  return (size ?? 0) as number',
    scope: 'packages/host',
  },
  {
    id: 'preset-tier-needs-gains',
    why: '档位表没配 P/T 就拒。拆掉 ⇒ undefined 当增益写进硬件（出厂表六档全是空的，这条路每次都会走到）',
    file: `${K}/zctrl-preset.ts`,
    find: '  return p === undefined || p === null || t === undefined || t === null ? null : [p, t]',
    replace: '  return [(p ?? 0) as number, (t ?? 1) as number]',
    scope: 'packages/host',
  },
  {
    id: 'apply-preset-stops-on-gain-failure',
    why: '增益没写进去就不写设定点。拆掉 ⇒ 半组参数落地：增益是旧的、设定点是新的，而返回值看起来只是「设定点失败」',
    file: `${SK}/l0/zctrl-presets.ts`,
    find: '      if (!gainRes.success) {',
    replace: '      if (false && !gainRes.success) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'approach-preset-restores',
    why: '缺陷⑫：进针改过的增益必须放回去。拆掉 ⇒ 进针组的快增益一路带进成像，而没人知道它是谁改的',
    file: `${SK}/composite/approach-preset.ts`,
    find: "      const res = await ctx.runSkill('SetZCtrlGain', { ...snapshot.gains })",
    replace: '      const res: SkillResultLike = { success: true }',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'approach-preset-soft-stop-keeps-setpoint',
    why: '软停时**不还设定点**（缺陷⑬ 要求四）。拆掉 ⇒ 一个刚被叫停的流程以「归还」的名义再动一次针',
    file: `${SK}/composite/approach-preset.ts`,
    find: '    if (sp !== null && operatorStopped(ctx)) {',
    replace: '    if (false && sp !== null && operatorStopped(ctx)) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'approach-preset-snapshot-on-failure',
    why: '切参数组失败也要返回快照 ——「调用失败」不等于「什么都没改」。拆掉 ⇒ 写了一半的参数组永远放不回去',
    file: `${SK}/composite/approach-preset.ts`,
    find: '    return [{ gains: before, setpointA: spBefore }, note]',
    replace: '    return [ok ? { gains: before, setpointA: spBefore } : null, note]',
    scope: 'packages/host/stm-skills',
  },
  // ── 批 3c：撞针判据与聚合读 ────────────────────────────────────────
  {
    id: 'crash-status-is-three-valued',
    why: '一路都没读到是 skipped，不是 ok。拆掉 ⇒ 「我没能看」被说成「我没发现撞针」，而下游拿它决定要不要接着扫',
    file: `${K}/crash-check.ts`,
    // `void readableAny` 是为了让它仍被引用 —— 本仓开着 `noUnusedParameters`，
    // 直接删掉那一支会让参数变成未使用、`tsc` 报错、演练判 inconclusive。
    find: "  return crash ? 'crash' : readableAny ? 'ok' : 'skipped'",
    replace: "  return crash ? 'crash' : (void readableAny, 'ok')",
    scope: 'packages/host',
  },
  {
    id: 'crash-nan-is-a-crash',
    why: '一整帧 NaN 就是撞针最典型的样子。只看极差 ⇒ NaN < eps 为假，最该报警的那一帧变成最安静的那一帧',
    file: `${K}/crash-check.ts`,
    // `||` 换 `&&` 而不是把 `hasNan` 整个删掉：后者让它变成未使用的变量、编不过。
    find: '    if (hasNan || range < CRASH_RANGE_EPS) {',
    replace: '    if (hasNan && range < CRASH_RANGE_EPS) {',
    scope: 'packages/host',
  },
  {
    id: 'crash-bad-channel-token-skipped',
    why: '通道清单里夹了个错字，跳过它继续。拆掉 ⇒ 一个错字让整次撞针检测不做，而它本来只是少探一路',
    file: `${K}/crash-check.ts`,
    find: '    if (!/^[+-]?\\d+$/.test(t)) continue',
    replace: '    if (Number.isNaN(Number(t))) continue',
    scope: 'packages/host',
  },
  {
    id: 'readmany-lists-unreadable',
    why: '聚合读里读不到的那几格要单列。拆掉 ⇒ null 既可能是「没配」也可能是「没问到」，而两者长得一模一样',
    file: `${SK}/l0/reads-config.ts`,
    find: "  if (failed.length > 0) out['_unreadable'] = failed",
    replace: '  void failed',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'readmany-one-failure-keeps-the-batch',
    why: '一格读失败只置空它自己。拆掉 ⇒ 一个没装的模块把整批设置全带走，而其余十几格本来都读到了',
    file: `${SK}/l0/reads-config.ts`,
    find: '      failed.push(key)',
    replace: "      return { success: false, error: rec.error ?? '' }",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'tipshaper-naming-is-all-or-nothing',
    why: '长度对不上就一个都不具名。拆掉 ⇒ 「能对上几个先对几个」看起来很权威，而分歧点之后每个字段都悄悄错位',
    file: `${SK}/l0/reads-config.ts`,
    // 变异改成「只在**多**的时候拒」，于是少的那一侧会「能对上几个先对几个」——
    // 那正是这段注释说的更坏的失败，而且它编得过。
    find: '  if (props.length !== TIP_SHAPER_PROPS.length) {',
    replace: '  if (props.length > TIP_SHAPER_PROPS.length) {',
    scope: 'packages/host/stm-skills',
  },
  // ── 批 3d：锁相与留痕 ──────────────────────────────────────────────
  {
    id: 'lockin-values-before-modulation',
    why: '先设频率/幅度/相位，最后才开调制。倒过来 ⇒ 隧道结被上一次残留的幅度激励一小段时间（2026-07-03 复盘）',
    file: `${SK}/l0/lockin.ts`,
    // 把开关**提到最前面**（旧仓那一版就是这样），于是调制会先带着上一次残留的
    // 幅度/频率打开一小段时间。单行替换，编得过，而且正是那个缺陷的形状。
    find: "    const modOn = params['mod_on'] === true",
    replace:
      "    const modOn = params['mod_on'] === true; await ctx.safeCall('LockIn_ModOnOffSet', 1, modOn ? 1 : 0)",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'lockin-zero-amplitude-is-a-value',
    why: '幅度 0 是「开之前先把它变安全」，必须写得下去。拆掉 ⇒ 这件事做不到，而调用方以为做到了',
    file: `${SK}/l0/lockin.ts`,
    find: "    if (given(params, 'amplitude_v') && n(params, 'amplitude_v') >= 0) {",
    replace: "    if (given(params, 'amplitude_v') && n(params, 'amplitude_v') > 0) {",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'lockin-unwritten-field-is-null',
    why: '没写的字段报 null。拆掉 ⇒ 返回值宣称了一个相位，而那个寄存器它根本没碰过',
    file: `${SK}/l0/lockin.ts`,
    find: "      phase_deg: phaseWritten ? n(params, 'phase_deg') : null,",
    replace: "      phase_deg: n(params, 'phase_deg'),",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'lockin-demod-null-means-unset',
    why: '模型那条路上每个可选字段都以 null 到达。用 `in` 判 ⇒ 把 null 送进硬件 setter（真机上是写坏的写入）',
    file: `${SK}/l0/lockin.ts`,
    find: '  p[k] !== undefined && p[k] !== null',
    replace: '  k in p',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'lockin-readback-unreadable-is-null',
    why: '六个读回字段读不到时给 null。拆掉 ⇒ 0 被当成读数，而 modulated_signal 读错会让一条完全干净的曲线不是 dI/dV',
    file: `${SK}/l0/lockin.ts`,
    find: '      data[key] = failed(rec) ? null : scalarInt(rec.values ?? null)',
    replace: '      data[key] = scalarInt(rec.values ?? null) ?? 0',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'datalog-channels-are-strict',
    why: '记的是哪几路，一个记号不是整数就整串作废。拆掉 ⇒ 默默丢掉一路，日志里少一个通道而没人知道',
    file: `${SK}/l0/datalog-marks.ts`,
    find: '    if (!/^[+-]?\\d+$/.test(t)) return null',
    replace: '    if (!/^[+-]?\\d+$/.test(t)) continue',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'datalog-timed-vs-continuous',
    why: '给了时长就是定时，没给才是连续。拆掉 ⇒ 一次本该定时的日志一直写到磁盘满',
    file: `${SK}/l0/datalog-marks.ts`,
    // `void MODE_TIMED` 让它仍被引用 —— 直接删掉那一支会让常量变成未使用、编不过。
    find: '    const mode = total > 0 ? MODE_TIMED : MODE_CONTINUOUS',
    replace: '    const mode = (void MODE_TIMED, MODE_CONTINUOUS)',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'marks-line-needs-both-ends',
    why: '线标记缺终点就拒。拆掉 ⇒ 拿起点当终点画一条零长的线，而留痕的全部意义是「在哪里」',
    file: `${SK}/l0/datalog-marks.ts`,
    find: "      if (!(typeof params['x2_m'] === 'number') || !(typeof params['y2_m'] === 'number')) {",
    replace: '      if (false) {',
    scope: 'packages/host/stm-skills',
  },

  // ── 批 3e：锁相参数组 + 相位对齐 ────────────────────────────────────
  {
    id: 'lockin-preset-no-factory-default',
    why: '档案没填就不下发（D-LOCKIN-2）。拆掉 ⇒ 一个出厂默认的 20 mV 调制以「本机标定」的名义加到谁也没确认过的隧道结上',
    file: `${K}/lockin-preset.ts`,
    find: '  return raw === null || raw === undefined || !Number.isFinite(raw) ? null : raw',
    replace: '  return raw === null || raw === undefined || !Number.isFinite(raw) ? 0.02 : raw',
    scope: 'packages/host',
  },
  {
    id: 'lockin-preset-phase-never-sent',
    why: '调制侧 phase 永不进调用序列（D-LOCKIN-1，固件恒拒、写同值也拒）。往组里塞一个 ⇒ 看谁拦得住',
    file: `${K}/lockin-preset.ts`,
    find: '    return { mod_on: modOn, ...this.values }',
    replace: '    return { mod_on: modOn, ...this.values, phase_deg: 0 }',
    scope: 'packages/host',
  },
  {
    id: 'lockin-readback-key-map',
    why: '组里叫 amplitude_v、回包里叫 amplitude（旧仓缺陷⑩）。改成同名 ⇒ 每一次成功写入都被报成「读不回来」，而那句失败带着「我核对过」的口气',
    file: `${K}/lockin-preset.ts`,
    find: "  amplitude_v: 'amplitude',",
    replace: "  amplitude_v: 'amplitude_v',",
    scope: 'packages/host',
  },
  {
    id: 'lockin-apply-readback-blocks',
    why: '下发后回读不一致 ⇒ 失败。拆掉 ⇒ 一次硬件没收下的调制幅度挂着「已设置」的牌子，而 dI/dV 曲线照样画得出来',
    file: `${SK}/l0/lockin-presets.ts`,
    find: '      if (mismatches.length > 0) {',
    replace: '      if (false) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'autophase-pymod-not-remainder',
    why: 'Python 取模、不是 JS 取余。改成取余 ⇒ 相位目标差 360°（−170° 起、−90° 增量给 −260° 而不是 +100°），而硬件会自己折回去，于是写进去的和报出来的不是一个数',
    file: `${K}/phase-align.ts`,
    find: '  return r < 0 !== n < 0 ? r + n : r',
    replace: '  return r',
    scope: 'packages/host',
  },
  {
    id: 'autophase-noise-floor',
    why: '噪声底上判不了相位就不写。把下界降到 0 ⇒ 一个由噪声算出来的角被写进硬件，而它和真的相位角一样体面',
    file: `${K}/phase-align.ts`,
    find: 'export const AUTOPHASE_MIN_SIGNAL = 1e-12',
    replace: 'export const AUTOPHASE_MIN_SIGNAL = 0',
    scope: 'packages/host',
  },
  {
    id: 'autophase-phase-readback-tol',
    why: '相位回读的 0.5° 绝对容差。放到 1e9 ⇒ 写了 26° 回读 12° 也算「已对齐」',
    file: `${K}/phase-align.ts`,
    find: 'export const PHASE_READBACK_TOL_DEG = 0.5',
    replace: 'export const PHASE_READBACK_TOL_DEG = 1e9',
    scope: 'packages/host',
  },
  {
    id: 'pysum-neumaier',
    why: 'CPython 3.12 起 sum() 对浮点用 Neumaier 补偿求和。拆掉补偿 ⇒ 均值在最后两位上与旧仓分岔，而金样是逐字节比的',
    file: `${K}/si.ts`,
    find: '    comp += Math.abs(sum) >= Math.abs(x) ? sum - t + x : x - t + sum',
    replace: '    comp += 0',
    scope: 'packages/host',
  },
  {
    id: 'autophase-abort-writes-nothing',
    why: '中止时什么都不写（连收尾关调制也不发）。拆掉 ⇒ 往一套正在跑的急停序列里插一条写操作',
    file: `${SK}/l0/lockin-presets.ts`,
    find: "      if (res.data?.['aborted'] === true) return res",
    replace: '      if (false) return res',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'autophase-closes-modulation',
    why: '缺陷⑪：它是这条链的终端消费者，跑完要把调制关回 OFF。拆掉 ⇒ 调制留着，在电流通道上叠一层纹波，污染后面每一条判据',
    file: `${SK}/l0/lockin-presets.ts`,
    find: "      const note = await closeModulation(ctx, 'AutoPhase')",
    replace:
      '      const note = ((): Record<string, unknown> => (void closeModulation, {}))()',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'autophase-never-guesses-indices',
    why: 'X/Y 走哪两路 RT 信号是接线事实，两处都没配就拒。改成猜 0 ⇒ 读到的是另一路信号，而算出来的角度看上去一样合理，然后被写进硬件',
    file: `${SK}/l0/lockin-presets.ts`,
    find: "  if (x !== null && y !== null) return { x, y, why: '' }",
    replace: "  return { x: x ?? 0, y: y ?? 0, why: '' }",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'autophase-needs-current-phase',
    why: 'atan2 算出来的是增量，读不到起点就不写。编一个 0 起点 ⇒ 相位被转到一个谁也没要的地方',
    file: `${SK}/l0/lockin-presets.ts`,
    find: '  const current = failedCall(recCur) ? null : num(recCur, 0)',
    replace: '  const current = failedCall(recCur) ? 0 : num(recCur, 0) ?? 0',
    scope: 'packages/host/stm-skills',
  },

  // ── 批 3e：五个收口模块 ─────────────────────────────────────────────
  {
    id: 'atomtrack-enable-failure-is-failure',
    why: '开调制失败就是整趟失败。咽下去 ⇒ 调用方相信调制与控制器已经开着，而它们没有',
    file: `${SK}/l0/atom-track.ts`,
    find: '      if (failed(rec)) return fail(`enable modulation failed: ${rec.error ?? \'\'}`)',
    replace: '      if (false) return fail(`enable modulation failed: ${rec.error ?? \'\'}`)',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'atomtrack-status-from-body',
    why: '状态位在 body 第 0 位。读不到它 ⇒ 每一项 Atom Tracking 控制都报 Off，而这个读从来没看过硬件',
    file: `${SK}/l0/atom-track.ts`,
    find: '      status: (int(rec, 0) ?? 0) !== 0,',
    replace: '      status: (void int(rec, 0), false),',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'osci-needmodule-vs-link-error',
    why: '带 NeedModule 是配置问题，别的错是线路故障。合成一种 ⇒ 一次断链被报成「去 Nanonis 里打开那个模块」，而重连一百次也没用的那句建议给错了对象',
    file: `${SK}/l0/osci.ts`,
    find: "  return failed(rec) && isNeedModule(rec.error ?? '')",
    replace: '  return (void isNeedModule, failed(rec))',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'osci-samples-all-or-nothing',
    why: '一条采样里有一个点解不出就整条作废。改成跳过 ⇒ 一条中间掉了几个点的时间序列，形状看起来完全正常，而后面每个 FFT 峰位都按等间隔算',
    file: `${SK}/l0/osci.ts`,
    find: '    if (x === null) return null',
    replace: '    if (x === null) continue',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'spectrum-zero-is-a-value',
    why: '矩形窗(0)与不平均(0)都是声明里写着的合法值（D-ZERO-1）。把 0 当「没给」⇒ 这两个一次也下发不出去，而调用方以为下发了',
    file: `${SK}/l0/spectrum.ts`,
    find: '  typeof p[k] === \'number\' && Number.isFinite(p[k] as number) ? Math.trunc(p[k] as number) : dflt',
    replace: "  typeof p[k] === 'number' && p[k] !== 0 ? Math.trunc(p[k] as number) : dflt",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'spectrum-band-lo-lt-hi',
    why: '频段下界 ≥ 上界就拒。拆掉 ⇒ 一对反过来的游标，而 band_rms 报的是一个谁也没要的频段里的噪声',
    file: `${SK}/l0/spectrum.ts`,
    find: '    if (lo >= hi) {',
    replace: '    if (false) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'biassweep-limits-swapped',
    why: '颠倒的偏压限值换过来（与频带那条刻意不同：这里方向是另一个参数）。拆掉 ⇒ Nanonis 收到一对反的限值',
    file: `${SK}/l0/bias-sweep.ts`,
    find: '    if (lo > hi) [lo, hi] = [hi, lo]',
    replace: '    if (false) [lo, hi] = [hi, lo]',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'biassweep-props-four-args',
    why: 'BiasSwp.PropsSet 只收四个实参（D-BIASSWP-1）。加回旧仓那个第五个 ⇒ 真机上一次 TypeError，RunBiasSweep 每次都停在第三步',
    file: `${SK}/l0/bias-sweep.ts`,
    find: "'BiasSwp_PropsSet', steps, period, autosave, 0)",
    replace: "'BiasSwp_PropsSet', steps, period, autosave, 0, period)",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'biassweep-zero-is-a-value',
    why: 'sweep_direction=0（上限→下限）与 z_hold=0（Z 控制器不变）都是合法值（D-ZERO-1）。把 0 当「没给」⇒ 这两个一次也选不出来',
    file: `${SK}/l0/bias-sweep.ts`,
    find: '  typeof p[k] === \'number\' && Number.isFinite(p[k] as number) ? Math.trunc(p[k] as number) : dflt',
    replace: "  typeof p[k] === 'number' && p[k] !== 0 ? Math.trunc(p[k] as number) : dflt",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'biaspulse-position-before-pulse',
    why: '脉冲留下永久痕迹，所以发之前读一次针尖在哪。拆掉 ⇒ 标记落在一个最多差一个刷新周期的缓存坐标上，而躲开坏片区全靠这些坐标',
    file: `${SK}/l0/bias-sweep.ts`,
    find: '    const spot = await tipXyFields(ctx)',
    replace: '    const spot = ((): Record<string, number> => (void tipXyFields, {}))()',
    scope: 'packages/host/stm-skills',
  },
  // ── 批 3f：脚本白名单（本仓唯一一道「人签过字」形态的闸）─────────────
  {
    id: 'script-allowlist-empty-means-no',
    why: '空清单 = 一个脚本都不许跑（fail-closed）。拆掉 ⇒ 「审核状态未知」被当成「通过」，而脚本跑在 RT 控制器上，本仓每一道闸在它内部都不生效',
    file: `${K}/script-allowlist.ts`,
    find: '  if (allow.size === 0) {',
    replace: '  if (false) {',
    scope: 'packages/host',
  },
  {
    id: 'script-allowlist-unvetted-slot',
    why: '槽位不在清单上就拒。改成「随便挑一个已批准的条目顶上」⇒ 一个没人读过的脚本以另一个脚本的名义跑起来',
    file: `${K}/script-allowlist.ts`,
    find: '  const entry = allow.get(slot)',
    replace: '  const entry = allow.get(slot) ?? allow.values().next().value',
    scope: 'packages/host',
  },
  {
    id: 'script-lut-range-is-enforced',
    why: 'LUT 的范围由审脚本的人写定（只有他知道脚本把这些数当什么单位用）。拆掉 ⇒ 一个 LUT 以毫米计的延时线脚本收到以微米计的数，台子开到硬限位上',
    file: `${K}/script-allowlist.ts`,
    find: '  if (entry.lutMin === null && entry.lutMax === null) return []',
    replace: '  return (void entry, [])',
    scope: 'packages/host',
  },
  {
    id: 'script-load-gate-is-inverted',
    why: '**本仓唯一一道反的闸**：LoadNanonisScript 拒绝往已审槽位里装别的脚本。把它改成正的 ⇒ 「槽位 3 已批准」从此什么也不表示',
    file: `${SK}/l0/script-files.ts`,
    find: '  return allow.has(slot)',
    replace: '  return !allow.has(slot)',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'script-lut-write-permission',
    why: '过审 ≠ 批准写 LUT（allow_lut_write）。拆掉 ⇒ 一个只被批准「按原样跑」的脚本被换了参数',
    file: `${SK}/l0/nanonis-script.ts`,
    find: '    if (!vetted.allowLutWrite) {',
    replace: '    if (false) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'script-run-leaves-a-record',
    why: '本仓看不见脚本内部，那条留痕是事后唯一能拿到的「跑了什么」。抹掉它那句话 ⇒ 事后解释不了这次运行',
    file: `${SK}/l0/nanonis-script.ts`,
    find: "        'MAST 的安全门/模式门/中止门在脚本内部均不生效。',",
    replace: "        '',",
    scope: 'packages/host/stm-skills',
  },

  // ── 批 3f：仪器限值 ─────────────────────────────────────────────────
  {
    id: 'zlimits-enable-failure-is-failure',
    why: '限值写进去了但没启用 ⇒ 整趟失败（Nanonis 原文：未启用时本函数无任何作用）。拆掉 ⇒ 一条什么也不做的限值挂着「已设置」的牌子',
    file: `${SK}/l0/limits.ts`,
    find: '      if (failed(recEn)) {',
    replace: '      if (false) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'zlimits-enabled-is-read-not-inferred',
    why: 'enable=false 时把启用状态**读回来**，不推断。改成推断 ⇒ 调用方以为一条收紧的限值在保护他，而它一个作用都没有',
    file: `${SK}/l0/limits.ts`,
    find: '  return flags === null ? null : flags[0] !== 0',
    replace: '  return (void flags, true)',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'zlimits-widened-is-tristate',
    why: '读不到改前的值时 widened 是 null。改成 false ⇒ 「没放宽」与「不知道有没有放宽」被折成同一句话，而放宽这件事的全部纪律就是它看得见',
    file: `${SK}/l0/limits.ts`,
    find: '    const widened = before === null ? null : hi > (before[0] as number) || lo < (before[1] as number)',
    replace: '    const widened = before === null ? false : hi > (before[0] as number) || lo < (before[1] as number)',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'piezo-limits-lo-lt-hi',
    why: '反过来的一对压电电压界就拒。拆掉 ⇒ 一对颠倒的界被下发，而过压会让压电**永久**退极化',
    file: `${SK}/l0/limits.ts`,
    find: '      if (lo >= hi) {',
    replace: '      if (false) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'limits-floats-all-or-nothing',
    why: '限值读不齐就整份作废。改成「有几个算几个」⇒ 半份限值，而它比没有限值更危险（读的人以为两端都有界）',
    file: `${SK}/l0/limits.ts`,
    find: '  return out.length >= n ? out.slice(0, n) : null',
    replace: '  return out.slice(0, n)',
    scope: 'packages/host/stm-skills',
  },

  // ── 批 3f：PLL ─────────────────────────────────────────────────────
  {
    id: 'pll-output-failure-is-failure',
    why: 'PLL 输出开不起来就是整趟失败（后面两个控制器无从谈起）。拆掉 ⇒ 调用方相信环锁上了，而 Δf 读的是噪声',
    file: `${SK}/l0/pll.ts`,
    find: "    const r = await ctx.safeCall('PLL_OutOnOffSet', mod, outputOn ? 1 : 0)\n    if (failed(r)) return fail(r.error ?? '')",
    replace: "    const r = await ctx.safeCall('PLL_OutOnOffSet', mod, outputOn ? 1 : 0)\n    if (false) return fail(r.error ?? '')",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'pll-given-not-in',
    why: '判「给了没有」用 != null 而不是 in。改回 in ⇒ 模型那条路上 schema 实例化出来的六个 null 被送进硬件 setter',
    file: `${SK}/l0/pll.ts`,
    find: '  p[k] !== undefined && p[k] !== null',
    replace: '  k in p',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'pll-unparsable-omits-the-key',
    why: '解不出的读回字段**不写这个键**。改成照写 ⇒ 空 body 上 `null !== 0` 报出一个 true，而那是一个从来没被读到过的开关状态',
    file: `${SK}/l0/pll.ts`,
    find: '  return v === null ? {} : { [key]: v !== 0 }',
    replace: '  return { [key]: v !== 0 }',
    scope: 'packages/host/stm-skills',
  },

  {
    id: 'tipxy-magnitude-guard',
    why: '超出 1 mm 的「坐标」是解析残渣不是位置。放开它 ⇒ 标记被画到离样品几光年的地方，下游每一次算范围都跟着炸',
    file: `${SK}/l0/tip-xy.ts`,
    find: 'export const TIP_XY_MAX_M = 1e-3',
    replace: 'export const TIP_XY_MAX_M = 1e30',
    scope: 'packages/host/stm-skills',
  },
  // ── 课时 4.1：数值底座（形态学 / 重采样 / 亚像素互相关）──────────────
  //
  // 这五条挡的都是**差一格**：拆掉之后每一个输出仍然是一个合法的数、一张合法的图。
  {
    id: "numerics-morph-dilation-reflects-se",
    why: "D-NUM-8：膨胀用**翻转过的**结构元（对偶要求偏移号相反）。同原点 ⇒ 偶数结构元下整张图沿两轴各平移一个像素 —— 而一张平移一个像素的形貌图看起来完全正常。奇数尺寸两者恰好一样，所以只有金样那一格 4×4 分得开",
    file: `${NU}/morphology.ts`,
    find: "se.rows - 1 - (se.rows >> 1), se.cols - 1 - (se.cols >> 1)",
    replace: "se.rows >> 1, se.cols >> 1",
    scope: 'packages/host/numerics',
  },
  {
    id: "numerics-interp-mirror-keeps-last-span",
    why: "D-NUM-10：scipy 的 `mirror` 在 `(n−1, n)` 这一段上根本不折坐标（外层判 `x > n−1`，内层判 `y >= n`）。先折 ⇒ 差一行，而 `order=1` 上两种做法完全同解，只有零容差的 `order=0` 看得见",
    file: `${NU}/interpolate.ts`,
    find: "return y >= n ? p - y : y",
    replace: "return y > n - 1 ? p - y : y",
    scope: 'packages/host/numerics',
  },
  {
    id: "numerics-interp-wrap-period-is-n-minus-1",
    why: "D-NUM-9：插值族的 `wrap` 周期是 `n−1`（首尾重合），滤波族是 `n`。退化成滤波族那一条 ⇒ 同一个字符串在同一个库里被当成了同一件事，而 scipy 里它不是",
    file: `${NU}/interpolate.ts`,
    find: "const sz = n - 1",
    replace: "const sz = n",
    scope: 'packages/host/numerics',
  },
  {
    id: "numerics-subpixel-dftshift-is-fix",
    why: "D-NUM-14 的钉子：上采样中心用 `trunc` 不是 `round`。改一个 ⇒ 亚像素位移整体偏 `1/uf`，而它仍然是一个「合法」的数 —— 漂移补偿会稳定地往同一个方向多走一点",
    file: `${NU}/fft.ts`,
    find: "const dftshift = Math.trunc(ups / 2)",
    replace: "const dftshift = Math.round(ups / 2)",
    scope: 'packages/host/numerics',
  },
  {
    id: "numerics-xcorr-damps-tiny-magnitudes",
    why: "D-NUM-13：相位归一化的分母压到 `100·eps`，与 skimage 对齐。去掉 ⇒ 在几乎平坦的一对帧上与 skimage 分岔。⚠️ 这一条第一次跑是**绿的** —— 那一改当时没有任何测试在看，补上 `near_flat` 金样才变红",
    file: `${NU}/fft.ts`,
    find: "Math.max(Math.hypot(cr, ci), 100 * EPS)",
    replace: "Math.hypot(cr, ci)",
    scope: 'packages/host/numerics',
  },
  // ── 课时 4.1 续（数值缺件：find_peaks / pcov / correlate2d）─────────────
  //
  // 这七条挡的都是**语义**，不是精度：拆掉之后每一条曲线仍然有峰、每一张相关面
  // 仍然有个最大值、每一根误差棒仍然是一个合理的数。
  // 分辨它们的不是容差，是**特意造出来能分辨的那几格金样**。
  {
    id: 'numerics-findpeaks-prominence-is-the-lower-base',
    why: "prominence = 峰高 − **两侧最小值的较大者**。取较小者 ⇒ 每个峰都偏突出（走到全局最低点那一侧几乎总是 0），一座大山肩上的小凸起会拿到和主峰一样的份量。金样 `peaks.prominence_side` 那一格是专为这件事造的：max ⇒ 0.4，min ⇒ 0.7，**两个都是合理的数**",
    file: `${NU}/peaks.ts`,
    find: 'prom[p] = h - Math.max(leftMin, rightMin)',
    replace: 'prom[p] = h - Math.min(leftMin, rightMin)',
    scope: 'packages/host/numerics',
  },
  {
    id: 'numerics-findpeaks-plateau-midpoint-floors',
    why: '等高平台的峰位取中点**向下**取整（同 scipy）。改成向上 ⇒ 偶数宽的平台整体偏一格，而奇数宽的完全同解 —— 金样 `peaks.plateau_even`（四格宽）是唯一分得开的那一格',
    file: `${NU}/peaks.ts`,
    find: 'mid.push((i + (ahead - 1)) >> 1)',
    replace: 'mid.push(Math.ceil((i + (ahead - 1)) / 2))',
    scope: 'packages/host/numerics',
  },
  {
    id: 'numerics-findpeaks-distance-keeps-the-taller',
    why: '`distance` 从**最高**的峰往下处理，于是近处的矮峰被挤掉。反过来从最矮的开始 ⇒ 一个矮卫星把它旁边的主峰挤掉，而剩下的仍然是一组间隔合规的峰。金样 `peaks.hist_modes` 那一格里主峰 106 与卫星 114 相隔 8 < distance=12',
    file: `${NU}/peaks.ts`,
    find: 'for (let i = m - 1; i >= 0; i -= 1) {',
    replace: 'for (let i = 0; i < m; i += 1) {',
    scope: 'packages/host/numerics',
  },
  {
    id: 'numerics-curvefit-pcov-divides-by-dof',
    why: '`pcov = (JᵀJ)⁻¹·sse/(n−p)`，分母是**自由度**不是点数。写成 n ⇒ 每根误差棒小 2.6%（n=80、p=4）—— 一组完全合理的误差棒，而下游拿它判「这个峰显著吗」。判据不是容差，是「离 n−p 那个答案比离 n 那个近」（金样把写错的那一版也录了）',
    file: `${NU}/curve-fit.ts`,
    find: 'const s2 = cost / dof',
    replace: 'const s2 = cost / n',
    scope: 'packages/host/numerics',
  },
  {
    id: 'numerics-correlate2d-origin-is-half-of-size-minus-one',
    why: "`correlate2d(mode='same')` 的原点是 `(Mb−1)>>1`，而**同一个 scipy** 的 `grey_erosion` 是 `Mb>>1` —— 两个都叫「中心」，偶数核上差一格。猜错 ⇒ 整张相关面平移一格 ⇒ 漂移向量整体偏一个像素，而那仍是一个合法读数。奇数核完全同解，是金样里 2×2 与 4×4 两格逼出来的",
    file: `${NU}/correlate.ts`,
    find: 'const oy = (b.rows - 1) >> 1',
    replace: 'const oy = b.rows >> 1',
    scope: 'packages/host/numerics',
  },
  {
    id: 'numerics-xcorr-normalization-is-switchable',
    why: "相位归一化**可关**：旧仓 `drift_xcorr` 传的是 `normalization=None`（按功率加权，对 SPM 行噪声更稳），不是 skimage 缺省的 `'phase'`（每个频点一票）。写死成归一化 ⇒ 开关还在签名里、还能传 null、还不报错，而它什么也不做。两档只有在**几乎平坦的一对帧**上给不同答案：`'phase'` 报虚构的 (5,5)，null 报 (0,0)",
    file: `${NU}/fft.ts`,
    find: "reference, moving, normalization === 'phase',",
    replace: 'reference, moving, true,',
    scope: 'packages/host/numerics',
  },
  {
    id: 'numerics-xcorr-conjugates-the-upsampled-peak',
    why: '亚像素那一路对 `conj(互功率谱)` 做上采样 DFT，**结果要再取一次共轭**（skimage 如此）。上一版把它略掉过，理由是「只用 `|·|` 找峰，共轭不改模长」—— 那在只回 `shift` 的时候成立。接口一旦多回一个 `phase`，这一步就略不掉了：共轭把辐角整个变号。只有 `b = −a` 那一格分得开（对得上的帧 phase 恒为 0）',
    file: `${NU}/fft.ts`,
    find: 'const ccIm = -(fine.im.data[at] as number)',
    replace: 'const ccIm = fine.im.data[at] as number',
    scope: 'packages/host/numerics',
  },
  {
    id: 'numerics-savgol-row-scaling-also-scales-y',
    why: '`savgol_coeffs` 的行缩放要**连右端 y 一起缩**，否则解的是另一个方程。少缩这一下 ⇒ 系数整体差一个常数因子，滤出来的曲线**仍然光滑**、形状也对，只是整条被缩放了 —— 而下游拿它去找峰、量半高宽。零容差的那条「系数和为 1」当场红',
    file: `${NU}/savgol.ts`,
    find: 'y[0] = 1 / (scale[0] as number)',
    replace: 'y[0] = 1',
    scope: 'packages/host/numerics',
  },
  {
    id: 'numerics-savgol-refits-both-edges',
    why: "`mode='interp'` 下两端各 `w//2` 个点**不经过那串系数**，要对最外 w 个样本重做一次 polyfit。少做右边那一次 ⇒ 最后几个点退回补零卷积，被拉向 0 —— 而一条谱的最外几个点正是「有没有能隙」要看的地方",
    file: `${NU}/savgol.ts`,
    find: 'fitEdge(x, n - windowLength, n, n - half, n, polyorder, out)',
    replace: 'fitEdge(x, n - windowLength, n, n, n, polyorder, out)',
    scope: 'packages/host/numerics',
  },
  {
    id: 'numerics-polyfit-scales-its-columns',
    why: 'numpy 的 `polyfit` 先把设计阵每列除以自己的 2-范数再解。不缩放**不改数学解**，只让条件数退化到 `κ²` 那一档 —— 于是我们与 numpy 的差从「实测水平」掉到「保证」那一档，而那时「是不是算错了」和「是不是病态」分不开。⚠️ 这一条挡的是**精度的量级**不是对错，是这一层唯一一条这种形状的闸',
    file: `${NU}/savgol.ts`,
    find: 'scale[j] = Math.sqrt(acc)',
    replace: 'scale[j] = 1',
    scope: 'packages/host/numerics',
  },
  // ── 课时 4.2：nanonis 文件读（.sxm / .dat / .3ds）─────────────────────
  //
  // 这六条挡的都是**同一种事故**：读错了不会抛，只会得到一张看起来很正常的图。
  {
    id: '3ds-missing-pixels-are-nan-not-zero',
    why: 'D-3DS-1：网格没跑完的那几个像素填 NaN。改回旧仓的补零 ⇒ 一片「谱强度恒为零」的区域，在自动流程里长得像一块干净的样品 —— 形状对、dtype 对、值是合法浮点，没有任何外部可见的信号',
    file: `${NF}/threeds.ts`,
    find: '      gRow.push(new Float64Array(nPoints).fill(NaN))',
    replace: '      gRow.push(new Float64Array(nPoints))',
    scope: 'packages/host/nanonis-files',
  },
  {
    id: '3ds-pixels-written-is-counted-not-declared',
    why: 'D-3DS-1 的另一半：交出去的是**数出来的**已写像素数。改成交头里声明的那个数 ⇒ `pixels_missing` 恒为 0，于是「网格没跑完」这件事再也没人读得到，而它正是这条偏差存在的全部理由',
    file: `${NF}/threeds.ts`,
    find: '      pixels_written: written,',
    replace: '      pixels_written: nx * ny,',
    scope: 'packages/host/nanonis-files',
  },
  {
    id: 'sxm-direction-decides-frame-count',
    why: '每通道的 Direction 决定这个通道存 1 帧还是 2 帧（旧仓 2026-07-03 复盘）。一律读两帧 ⇒ 字节偏移错位，**后面每一个通道的数据都被移位** —— 而每一帧本身仍是一张合法的图',
    file: `${NF}/sxm.ts`,
    find: "  if (hasFwd && !hasBwd) return ['forward']",
    replace: "  if (false && hasFwd && !hasBwd) return ['forward']",
    scope: 'packages/host/nanonis-files',
  },
  {
    id: 'sxm-negative-pixels-are-not-zero-pixels',
    why: '判据 ②：`<= 0` 不是 `== 0`。负的像素数会被当成「-1 你猜」，从任意字节里 reshape 出一帧来 —— 那一帧有正确的 dtype 和一个自洽的形状',
    file: `${NF}/sxm.ts`,
    find: '  if (nx <= 0 || ny <= 0) return { header, channels: {} }',
    replace: '  if (nx === 0 || ny === 0) return { header, channels: {} }',
    scope: 'packages/host/nanonis-files',
  },
  {
    id: 'dat-mode-width-breaks-ties-by-first-seen',
    why: '`.dat` 列宽取众数，并列时取**先出现**的那个（同 `Counter.most_common`）。取后出现的 ⇒ 一条落单的坏行能把整份数据的列宽带偏，而结果仍是一组长度整齐的列',
    file: `${NF}/dat.ts`,
    find: '      if (c > best) {',
    replace: '      if (c >= best) {',
    scope: 'packages/host/nanonis-files',
  },
  {
    id: 'file-size-gate-is-gt-not-gte',
    why: '尺寸闸刚好等于上限要放行。改成 `>=` ⇒ 一个恰好 2 GiB 的文件被拒，而拒绝的理由（「太大」）是假的 —— 这条挡的不是内存，是**一句说不清的拒绝**',
    file: `${NF}/common.ts`,
    find: '  if (byteLength > MAX_FILE_BYTES) {',
    replace: '  if (byteLength >= MAX_FILE_BYTES) {',
    scope: 'packages/host/nanonis-files',
  },
  // ── 批 3g（optional_* 五族）的演练写在这一行下面 ──
  {
    id: 'hsswp-zero-means-continuous',
    why: 'num_sweeps=0 是声明里写着的「一直扫到被停止」（D-ZERO-1 第四次）。把 0 当「没给」⇒ 一次「扫到我喊停」安安静静地变成扫一次，而调用方以为它还在扫',
    file: `${SK}/l0/optional-sweepers.ts`,
    find: "    const n = given(params, 'num_sweeps') ? i(params, 'num_sweeps') : 1",
    replace: "    const n = i(params, 'num_sweeps') || 1",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'pi-limits-before-tuning',
    why: '输出限**先写**：后面任何一步失败时，手上都已经是一组带界的参数。挪到最后 ⇒ 一个整定好了、界还停在上一次（可能大开）的环',
    file: `${SK}/l0/optional-controllers.ts`,
    find: "    let s = await step(ctx, 'PICtrl_CtrlChPropsSet', idx, lo, hi)\n    if (s.error !== null) return fail(s.error)\n\n    s = await step(ctx, 'PICtrl_InputChSet', idx, i(params, 'input_index'))",
    replace: "    let s = await step(ctx, 'PICtrl_InputChSet', idx, i(params, 'input_index'))\n    if (s.error !== null) return fail(s.error)\n\n    s = await step(ctx, 'PICtrl_CtrlChPropsSet', idx, lo, hi)",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'pi-inverted-limits-refused',
    why: '反了的一对输出限就拒。拆掉 ⇒ 环立刻把输出推到轨上，而那一路输出可能是压电、偏压或加热器 —— 模块自己不知道是哪一种',
    file: `${SK}/l0/optional-controllers.ts`,
    find: '    if (lo >= hi) {\n      return fail(\n        `output_lower_limit',
    replace: '    if (false) {\n      return fail(\n        `output_lower_limit',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'kelvin-inverted-limits-refused',
    why: '反了的一对偏压界就拒。拆掉 ⇒ Kelvin 环立刻把偏压推到轨上，而这个环是自主驱动偏压的',
    file: `${SK}/l0/optional-afm.ts`,
    find: '    if (lo >= hi) {\n      return fail(\n        `bias_low_limit_v',
    replace: '    if (false) {\n      return fail(\n        `bias_low_limit_v',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'probe-gain-pair-preserved',
    why: '只给 P 时把 I 读回来保住。改成按 0 顶上 ⇒ I 增益归零就是一个死环：它看上去还开着，实际上再也追不上设定点',
    file: `${SK}/l0/optional-multiprobe.ts`,
    find: "        given(params, 'i_gain') ? f(params, 'i_gain') : Number(pair[1]),",
    replace: "        given(params, 'i_gain') ? f(params, 'i_gain') : 0,",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'rf-stop-cuts-output-anyway',
    why: '停扫失败时**更要**切输出 —— 一次失败的停扫正是你最需要把 RF 关掉的时候。改成前一条失败就返回 ⇒ 最危险的那一格恰好走不到第二条',
    file: `${SK}/l0/optional-sweepers.ts`,
    find: "    const sweepErr = failed(swp) ? (swp.error ?? '') : ''",
    replace: "    const sweepErr = failed(swp) ? (swp.error ?? '') : ''\n    if (sweepErr !== '') return fail(sweepErr)",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'rf-sweep-never-infinite',
    why: 'RF 频率扫描的 Infinite 位永远写 0（与 HSSwp 刻意相反）。翻起来 ⇒ 一次无限的扫描持续往隧道结里灌功率，而智能体对多少算多没有手感',
    file: `${SK}/l0/optional-sweepers.ts`,
    find: '      0, // Infinite —— 见上',
    replace: '      1, // Infinite —— 见上',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'psd-failure-keeps-the-trace',
    why: 'PSD 读不到不许把已经在手的曲线扔掉。改成整趟失败 ⇒ 拿有的东西换没有的，而「没取到 PSD」与「什么都没取到」被折成同一句话',
    file: `${SK}/l0/optional-scopes.ts`,
    find: "      if (failed(psd)) data['psd_error'] = String(psd.error ?? '')",
    replace: "      if (failed(psd)) return fail(String(psd.error ?? ''))",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'preamp-nothing-given-is-refused',
    why: '三项一个都不给就拒。拆掉 ⇒ 一次「什么都没改」的成功，和一次改好了的成功，在返回值上长得一模一样',
    file: `${SK}/l0/optional-controllers.ts`,
    find: "    if (touched.length === 0) return fail('gain / coupling / input_mode 至少要给一个')",
    replace: "    if (false) return fail('gain / coupling / input_mode 至少要给一个')",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'optional-multiread-null-not-zero',
    why: '聚合读里一格读不到给 null。改成给 0 ⇒ 「没问出来」变成一个读数，而这一族里那些 0 会被当成「环是关的」「增益是零」',
    file: `${SK}/l0/optional-common.ts`,
    find: '    data[key] = failed(rec) ? null : cell(rec)',
    replace: '    data[key] = failed(rec) ? 0 : cell(rec)',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'beam-deflection-unknown-axis',
    why: '认不出的轴就拒。改成落到 vertical ⇒ 一次本想标定 sum 的调用把垂直轴的标定改了，而返回里写着你要的那个轴名',
    file: `${SK}/l0/optional-afm.ts`,
    find: '            : ([null, null] as const)',
    replace: "            : (['BeamDefl_VerConfigSet', await ctx.safeCall('BeamDefl_VerConfigSet', ...sig)] as const)",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'optional-channels-all-or-nothing',
    why: '采集通道清单严格：一个记号不是整数就整串作废。改成跳过 ⇒ 默默丢掉一路，数据里少一个通道而没人知道（同 D-CHANNELS-1）',
    file: `${SK}/l0/optional-common.ts`,
    find: '    if (!/^[+-]?\\d+$/.test(t)) return null',
    replace: '    if (!/^[+-]?\\d+$/.test(t)) continue',
    scope: 'packages/host/stm-skills',
  },

  // ── 批 3h（输出 / 扫频 / 图样）的演练写在这一行下面 ──
  {
    id: 'userout-unreadable-limits-refuse',
    why: '用户输出的限值读不到就不写。拆掉 ⇒ 未知的包络被当成敞开的包络，而本仓根本不知道这个输出口接的是什么',
    file: `${SK}/l0/user-output.ts`,
    find: '    if (failed(lim)) {',
    replace: '    if (false) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'userout-honours-instrument-envelope',
    why: '越过仪器上配好的物理限值就拒。拆掉 ⇒ 一个可能驱动栅压、快门或延时线的通道被开到操作员没批准的地方',
    file: `${SK}/l0/user-output.ts`,
    find: '    if (!(lo <= value && value <= hi)) {',
    replace: '    if (false) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'userout-widened-is-recorded',
    why: '放宽护栏合法，但必须带着 widened 标志留痕。改成恒 false ⇒ 一次放宽和一次收紧在台账里长得一样，而这一族全部的纪律就是它看得见',
    file: `${SK}/l0/user-output.ts`,
    find: '    const widened = before !== null && (upper > before.upper || lower < before.lower)',
    replace: '    const widened = before !== null && false',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'userout-digital-line-range',
    why: '数字线号是端口内的 1..8。拆掉 ⇒ 越界那一条是另一个端口上的线，而本仓不知道那条线接着什么',
    file: `${SK}/l0/user-output.ts`,
    find: '    if (lines.length === 0 || lines.some((v) => !(v >= 1 && v <= 8))) {',
    replace: '    if (lines.length === 0) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'waveform-period-not-frequency',
    why: '双通道函数发生器收的是**周期**不是频率。直接透传 ⇒ 一次 1 kHz 的请求被设成 1000 秒的周期，差六个数量级，静悄悄地，在一台谁也看不见的硬件上',
    file: `${SK}/l0/waveform.ts`,
    find: '    const periodS = 1.0 / freq',
    replace: '    const periodS = freq',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'waitscan-slice-is-milliseconds',
    why: 'Scan_WaitEndOfScan 收的是毫秒。传秒 ⇒ 短等 1000 倍，然后在扫描刚开始的那一瞬间报告「扫描已结束」',
    file: `${SK}/l0/advanced-ops.ts`,
    find: '      const sliceMs = Math.max(1, Math.trunc(Math.min(SLICE_S * 1000, remainingMs)))',
    replace: '      const sliceMs = Math.max(1, Math.trunc(Math.min(SLICE_S, remainingMs)))',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'waitscan-unreadable-means-finished',
    why: '读不出超时位就当作「已结束」、退出等待。反过来猜 ⇒ 一次读取故障变成一次等满预算的长等待',
    file: `${SK}/l0/advanced-ops.ts`,
    find: "  return typeof first === 'number' && Math.trunc(first) === 1",
    replace: "  return typeof first !== 'number' || Math.trunc(first) === 1",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'quit-withdraw-is-not-optional',
    why: '退出 Nanonis 之前退针不是可选的。拆掉 ⇒ 带着进针状态退出，Z 反馈随进程一起死掉，针尖留在表面而没有任何软件看管',
    file: `${SK}/l0/advanced-ops.ts`,
    find: '    if (failed(withdraw)) {',
    replace: '    if (false) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'quit-verifies-against-rt-controller',
    why: '退针要向实时控制器确认，确认不了也拒（fail-closed）。拆掉 ⇒ 测量链路的失败成了危险动作的触发条件',
    file: `${SK}/l0/advanced-ops.ts`,
    find: '    if (!(v.verified && v.on === false)) {',
    replace: '    if (false) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'pattern-cloud-json-must-be-a-list',
    why: '合法 JSON 还不够：`"5"` 解出来是整数 5。拆掉 ⇒ 模型少写一对方括号就换来一个到不了 SkillResult 的异常——没有错误分支、没有重试，一个死掉的回合',
    file: `${SK}/l0/pattern.ts`,
    find: '      if (!Array.isArray(seq)) {',
    replace: '      if (false) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'spectroscopy-firstint-rejects-floats',
    why: '「谱学在不在跑」的状态位是整数。把浮点也收下 ⇒ 一个读不懂的回包变成一句确定的「没在跑」',
    file: `${SK}/l0/spectroscopy-sync.ts`,
    find: "    if (typeof x === 'number' && Number.isInteger(x)) return x",
    replace: "    if (typeof x === 'number') return Math.trunc(x)",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'sweep-rows-all-or-nothing',
    why: '取不到可解的曲线就给 null。改成给空数组 ⇒ 一次没取到数的扫描报成「扫到了，是平的」',
    file: `${SK}/l0/sweep.ts`,
    find: '  if (!Array.isArray(arr) || arr.length === 0) return null',
    replace: '  if (!Array.isArray(arr)) return null',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'sweep-acquire-turns-z-feedback-off',
    why: '偏压扫描期间必须断开 Z 反馈（定高）。改成不断开 ⇒ 扫到 0 V 附近时反馈把针尖压进表面',
    file: `${SK}/l0/sweep.ts`,
    find: "    const rec = await ctx.safeCall('GenSwp_Start', 1, 0, '', 1, 1)",
    replace: "    const rec = await ctx.safeCall('GenSwp_Start', 1, 0, '', 1, 0)",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'sweep-fallback-matches-declaration',
    why: '兜底值必须等于声明的缺省值。改回旧仓那个 20.0 ⇒ 组合路径上省略 period_ms 拿到的是 20，而模型/界面看到的广告是 4——广告与实际是两个积分时间',
    file: `${SK}/l0/sweep.ts`,
    find: 'const BIAS_SWEEP_PERIOD_MS = 4.0',
    replace: 'const BIAS_SWEEP_PERIOD_MS = 20.0',
    scope: 'packages/host/stm-skills',
  },


  // ── 批 3i（光学台 / 杂项 setter / 单件）的演练写在这一行下面 ──
  {
    id: 'piezo-unknown-is-not-ok',
    why: '仪器读不到压电范围 ⇒ unknown。折成 ok ⇒ 这个自检变成一句永远为真的安慰话，而 2026-08-16 那次正是没人去看一眼配置与实际差了 23%',
    file: `${K}/piezo-reconcile.ts`,
    find: '  return x === null || y === null ? null : [x, y]',
    replace: '  return [x ?? 0, y ?? 0]',
    scope: 'packages/host',
  },
  {
    id: 'piezo-two-axes-take-the-smaller',
    why: '两轴取小 —— 包络要保守。改成取大 ⇒ 放过一个 X 到不了的目标，而针尖会夹在限位上，移动以「超时」失败且重试无用',
    file: `${K}/piezo-reconcile.ts`,
    find: '  const instHalf = Math.min(pair[0], pair[1])',
    replace: '  const instHalf = Math.max(pair[0], pair[1])',
    scope: 'packages/host',
  },
  {
    id: 'qplus-excitation-needs-two-witnesses',
    why: '缺陷⑰：开关开着**并且**幅度 > 0 才算在驱动。只看开关 ⇒ 一台 STM 模式的机器上，未驱动解调器的噪声底被拿去跟自由振荡基线比，永远报「撞针」',
    file: `${K}/qplus-amplitude.ts`,
    find: '  return both[0] && both[1] > 0.0',
    replace: '  return (void excitationV, on)',
    scope: 'packages/host',
  },
  {
    id: 'qplus-unreadable-excitation-is-undecidable',
    why: '激励状态任一条读不到 ⇒ 判不了。折成「没驱动」⇒ 一个读不到 PLL 的机器上，撞针判据静静变成「不适用」而不是「我不知道」',
    file: `${K}/qplus-amplitude.ts`,
    find: '  return on === null || v === null ? null : [on, v]',
    replace: '  return [on ?? false, v ?? 0]',
    scope: 'packages/host',
  },
  {
    id: 'qplus-no-baseline-is-not-ok',
    why: '没有自由振荡基线 ⇒ no_baseline。折成 ok ⇒ 一个 0 V 的振幅被读成「针尖自由」，而 0 V 本身不表示任何事',
    file: `${K}/qplus-amplitude.ts`,
    find: '  return b === null || b <= 0 ? null : b',
    replace: '  return b ?? 1',
    scope: 'packages/host',
  },
  {
    id: 'qplus-amplitude-channel-needs-both-hints',
    why: '振幅通道要两组词都命中。只配 amplitude ⇒ 认到「幅度设定点」那类通道，于是撞针判据从此读的是一个常数，撞了也不会动',
    file: `${K}/qplus-amplitude.ts`,
    find: '  return AMP_HINTS.some((a) => low.includes(a)) && OSC_HINTS.some((o) => low.includes(o))',
    replace: '  return (void OSC_HINTS, AMP_HINTS.some((a) => low.includes(a)))',
    scope: 'packages/host',
  },
  {
    id: 'qplus-sentinel-is-not-an-index',
    why: '`-1` 是「自动发现」的哨兵，不是下标。当成下标用 ⇒ 把负通道号传给 Signals_ValGet，读到的是控制器对它做的任何事',
    file: `${K}/qplus-amplitude.ts`,
    find: '  return raw >= 0 ? Math.trunc(raw) : null',
    replace: '  return Math.trunc(raw)',
    scope: 'packages/host',
  },
  {
    id: 'scope-trigger-zero-is-a-value',
    why: '`trigger_mode = 0`（关触发）与 `trigger_slope = 0`（下降沿）都是声明里的合法值（D-ZERO-1 第三次）。把 0 当「没给」⇒ 这两个一次也下发不出去，而调用方以为下发了',
    file: `${SK}/l0/misc-setters.ts`,
    find: '  typeof p[k] === \'number\' && Number.isFinite(p[k] as number) ? Math.trunc(p[k] as number) : dflt',
    replace: "  typeof p[k] === 'number' && p[k] !== 0 ? Math.trunc(p[k] as number) : dflt",
    scope: 'packages/host/stm-skills',
  },

  // ── 批 3j（流式读回一族）的演练写在这一行下面 ──
  {
    id: 'z-trace-seg4-too-short-is-not-no-change',
    why: '第四段（反馈恢复段）太短/没录到时答案是**判不了**，不是「没扎上」。拆掉 ⇒ 用户被送去一次次加深扎入深度，而缺的其实是一秒钟采集时间；2026-08-20 的 168 条历史曲线里 160 条是这个形状，真簇被这样判掉了 62 %',
    file: `${K}/z-trace.ts`,
    find: "  if (seg4Source === 'too_short' || seg4Source === 'no_return') {",
    replace: "  if (false && (seg4Source === 'too_short' || seg4Source === 'no_return')) {",
    scope: 'packages/host',
  },
  {
    id: 'z-trace-no-return-is-not-no-press',
    why: '「电流从没升上去」与「升上去了再没回来」指向完全不同的下一步：前者照判（可能就是没扎上，而那是实话），后者判不了。合成一个词 ⇒ 后者被当成一次确定的判定',
    file: `${K}/z-trace.ts`,
    find: "  return { t: null, why: 'no_return' }",
    replace: "  return { t: null, why: 'no_press' }",
    scope: 'packages/host',
  },
  {
    id: 'z-trace-must-confirm-it-pressed-in',
    why: '定位第四段之前要先确认**压进去过**。拆掉 ⇒ 基线段自己就满足「电流等于 setpoint」，t4 落在扎针**之前**，于是判据拿扎针前的一段当扎针后的结果',
    file: `${K}/z-trace.ts`,
    find: '    if (currentT[k]! >= eventStartT && Math.abs(currentS[k]!) > CURRENT_PRESSED_K * i0) {',
    replace: '    if (currentT[k]! >= eventStartT && Math.abs(currentS[k]!) >= 0) {',
    scope: 'packages/host',
  },
  {
    id: 'z-trace-post-window-starved-fallback',
    why: '后窗按**点数**兜底。拆掉 ⇒ 一次 122 ms 的 TCP 卡顿把一次健康的 440 点采集判成 insufficient_data —— 手里握着 315 个好样本却说「我说不出针尖发生了什么」',
    file: `${K}/z-trace.ts`,
    find: '  const postStarved = postIdx.length < MIN_WINDOW_SAMPLES && samples.length >= MIN_WINDOW_SAMPLES',
    replace: '  const postStarved = false',
    scope: 'packages/host',
  },
  {
    id: 'z-trace-pre-window-has-no-fallback',
    why: '前窗**刻意不兜底**：它由 `t < eventStartT` 选出，没有被离群值挟持的失败模式，点数少就是基线**真的**不够。给它兜底 ⇒ 空基线上 z1 取成 0，任何 z3 都变成一次「巨大的跳变」',
    file: `${K}/z-trace.ts`,
    find: '  if (pre.length < 2 || post.length < 2) {',
    replace: '  if (post.length < 2) {',
    scope: 'packages/host',
  },
  {
    id: 'z-trace-insufficient-keeps-diagnostics',
    why: '判不出来时**保留全部诊断**。拆掉 ⇒ n_pre / n_post / max_gap_s 恰好在不需要它们时幸存、在需要它们时消失 —— 判不出来正是最想知道「采了几个点、最长往返多久」的时刻',
    file: `${K}/z-trace.ts`,
    find: '  const out = stepVerdictFields(iv.step)',
    replace: '  const out: Record<string, unknown> = {}',
    scope: 'packages/host',
  },
  {
    id: 'z-trace-windows-take-second-half',
    why: '两个窗口都只取**后半段**：扎入的下降沿、回撤的斜坡都发生在窗口前半，让它们渗进 z1/z3 会把稳定值算歪',
    file: `${K}/z-trace.ts`,
    find: '  const preS = pre.slice(pre.length >> 1)',
    replace: '  const preS = pre',
    scope: 'packages/host',
  },
  {
    id: 'z-trace-tol-has-an-absolute-floor',
    why: '`tol = max(tolAbsM, tolK·σ)` —— 绝对死区是**地板**。写成 min ⇒ 它变成天花板：一段安静得反常的基线（σ≈0）把容差压到 0，之后任何一点点差异都被判成「变了」',
    // ⚠️ 这一条本来写的是 `const tol = tolK * sigma1`，而那样 `tolAbsM` 就没人读了
    // ⇒ TS6133 ⇒ 构建失败 ⇒ **这道闸永远验不到**（本仓第 12 次撞到这个形状）。
    // 换成把地板改成天花板：判据同样被拆掉，而两个绑定都还有人读。
    file: `${K}/z-trace.ts`,
    find: '  const tol = Math.max(tolAbsM, tolK * sigma1)',
    replace: '  const tol = Math.min(tolAbsM, tolK * sigma1)',
    scope: 'packages/host',
  },
  {
    id: 'pyfixed-rounds-half-to-even',
    why: 'Python 的 `%.3f` 在半分点上取偶，`toFixed` 取大（0.0625 → 0.062 / 0.063）。半分点恰好是 1/16 的奇数倍，全是二进制精确表示的数 —— 语言分歧一族的第六个',
    file: `${K}/z-trace.ts`,
    find: '  if (Number.isInteger(scaled) && Math.abs(scaled % 10) === 5) {',
    replace: '  if (false && Number.isInteger(scaled) && Math.abs(scaled % 10) === 5) {',
    scope: 'packages/host',
  },
  {
    id: 'pulse-start-blocked-floor-is-20ms',
    why: '脉冲那边「固件忽略了 wait=0」的绝对下限是 **20 ms**，不是整形那边的 200 ms。照抄 200 ms ⇒ 这道守卫在任何短于 400 ms 的脉冲上**永远不触发** —— 守卫在，却只在不需要它的地方管用',
    file: `${SK}/l0/readback-skills.ts`,
    find: '    const startBlocked = capture.fireBlockedS >= Math.max(0.5 * widthS, 0.02)',
    replace: '    const startBlocked = capture.fireBlockedS >= Math.max(0.5 * widthS, 0.2)',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'shaper-bias-has-no-3v-fallback',
    why: '读不到当前偏压就**拒绝执行**，不回落到写死的 3 V。那个 3.0 追到 v1 移植时的 stub 占位，没有任何物理来源；2026-08-10 真机上它把用户设好的 20 mV 顶掉了',
    file: `${SK}/l0/readback-skills.ts`,
    find: '      const read = await shaperBiasDefault(ctx)',
    replace: '      const read = { ...(await shaperBiasDefault(ctx)), v: 3.0 }',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'shaper-bias-lift-follows-bias',
    why: '`Bias Lift (V)` 是**无条件**施加的（`change_bias` 解除不了它），省略时跟随 bias_v。写死 3.0 ⇒ 成像偏压降到 20 mV、回包写着 bias_v=0.02，而结上照样过了一记 3 V（用户范本要求的 150 倍）',
    file: `${SK}/l0/readback-skills.ts`,
    find: "    const biasLiftV = typeof params['bias_lift_v'] === 'number' ? (params['bias_lift_v'] as number) : biasV",
    replace: "    const biasLiftV = typeof params['bias_lift_v'] === 'number' ? (params['bias_lift_v'] as number) : 3.0",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'capture-signal-repeated-bits-anomaly',
    why: '几百个采样点**逐位相同**时那不是一次测量。拆掉 ⇒ 2026-07-27 现场那 600 个 std=0 的 z 又一次看起来完全合理，agent 读完就往下走',
    file: `${SK}/l0/readback-skills.ts`,
    find: '    if (n >= 8 && smax === smin) {',
    replace: '    if (false && n >= 8 && smax === smin) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'capture-signal-channel-is-a-python-int',
    why: "通道索引按 Python 的 `int()` 判——**只收十进制整数字面量**。放宽成 `Number()` ⇒ `'0x10'` 被收成 16，而旧仓那边是一次 ValueError（同批 3f 的 LUT 那一处）",
    file: `${SK}/l0/readback-skills.ts`,
    find: '      if (!/^[+-]?\\d+$/.test(channel.trim())) {',
    replace: '      if (Number.isNaN(Number(channel.trim()))) {',
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'lift-height-zero-is-a-real-height',
    why: '`lift_height_m = 0.0` 是「不抬」这个合法意图，不是「没给」（D-ZERO-1 又一次）。用 `|| null` 吃掉它 ⇒ 用户明确要求不抬，针却被抬回 −tip_lift_m',
    file: `${SK}/l0/tip-policy.ts`,
    find: "  const given = numOrNull(params['lift_height_m'])",
    replace: "  const given = (params['lift_height_m'] as number) || null",
    scope: 'packages/host/stm-skills',
  },

  // ── 批 3k（环境读）的演练写在这一行下面 ──

  // ── 批 3l（spectroscopy 整族）的演练写在这一行下面 ──

  // ── 批 4a（分析技能第一批）的演练写在这一行下面 ──
  {
    id: 'vac-allowlist-not-denylist',
    why: '真空计类名走**白名单**。改成黑名单 ⇒ 每一个未来的占位实现/陌生驱动都被默认接受，而它们报的那个 0.0 读起来正是完美真空',
    file: `${K}/vacuum-interlock.ts`,
    find: "  if (cls !== '' && !REAL_GAUGE_CLASSES.includes(cls)) {",
    replace: "  if (cls !== '' && PLACEHOLDER_CLASSES.includes(cls)) {",
    scope: 'packages/host',
  },
  {
    id: 'vac-status-must-be-ok',
    why: '`unavailable` 在告警路径上被**有意**忽略（掉线的规不该中止一整夜实验），在互锁上必须拦。拆掉 ⇒ 一只掉线的规报的 0.0 直接授权粗动',
    file: `${K}/vacuum-interlock.ts`,
    find: "  if (status !== 'ok') {",
    replace: "  if (false && status !== 'ok') {",
    scope: 'packages/host',
  },
  {
    id: 'vac-unknown-unit-is-refused',
    why: '认不出的单位一律拒。给个缺省倍数 1.0 ⇒ `1 mbar`（带正中、危险）与 `1 Pa` 进同一个桶，取决于哪只传感器碰巧应答',
    file: `${K}/vacuum-interlock.ts`,
    find: '  return mult === undefined ? null : val * mult',
    replace: '  return val * (mult ?? 1.0)',
    scope: 'packages/host',
  },
  {
    id: 'vac-no-timestamp-is-not-now',
    why: '没有时间戳 ⇒ 判不了新旧 ⇒ 拒。伪造一个 0 秒 ⇒ 任何 `age <= limit` 无条件通过，「不知道多旧」变成「刚刚读的」',
    file: `${K}/vacuum-interlock.ts`,
    find: "  if (ts === '') return null",
    replace: "  if (ts === '') return 0",
    scope: 'packages/host',
  },
  {
    id: 'vac-age-is-a-criterion',
    why: '五分钟前的读数对**现在**的压强什么都没说。拆掉年龄闸 ⇒ 抽气/放气途中拿一个旧读数给现在授权，而那正好是压强变化最快的时候',
    file: `${K}/vacuum-interlock.ts`,
    find: '  if (ageSec > cfg.maxAgeS) {',
    replace: '  if (false && ageSec > cfg.maxAgeS) {',
    scope: 'packages/host',
  },
  {
    id: 'vac-over-range-is-not-a-reading',
    why: '贴近满量程的规分不出「刚过一点」与「大气」，而 DL-7 的帧解析器不校验指数 —— 一次超量程能解码成一个像样的小数。拆掉 ⇒ 那个小数被当成好真空',
    file: `${K}/vacuum-interlock.ts`,
    find: '  if (cfg.fullScalePa > 0 && paValue >= cfg.fullScalePa * OVERRANGE_FRACTION) {',
    replace: '  if (false && cfg.fullScalePa > 0 && paValue >= cfg.fullScalePa * OVERRANGE_FRACTION) {',
    scope: 'packages/host',
  },
  {
    id: 'vac-under-range-depends-on-the-floor',
    why: '欠量程安不安全**取决于这只规的下限在哪**。一律当安全 ⇒ 一只 Pirani 触底时报的那个小数（在放电带里）被读成极好的真空 —— 这是换规那天才会暴露的一半',
    file: `${K}/vacuum-interlock.ts`,
    find: '    if (cfg.minPa >= cfg.maxPa) {',
    replace: '    if (false && cfg.minPa >= cfg.maxPa) {',
    scope: 'packages/host',
  },
  {
    id: 'vac-gauge-only-refuses-signatures',
    why: '`gauge_only` 模式下用户签署**不认**，而且要说出来。拆掉 ⇒ 一台被管理员设成「只认真空计」的机器上，一句签名照样能放行粗动',
    file: `${K}/vacuum-interlock.ts`,
    find: "  if (mode === 'gauge_only') {",
    replace: "  if (false && mode === 'gauge_only') {",
    scope: 'packages/host',
  },
  {
    id: 'vac-expired-signature-is-not-a-signature',
    why: '签署是**限时**的。不看过期 ⇒ 一份昨天签的「已通大气」在今天抽到中间真空时照样放行，而这正是签署要时限的全部理由',
    file: `${K}/vacuum-interlock.ts`,
    find: '    attestation !== null && !attestationExpired(attestation, nowS) ? attestation : null',
    replace: '    attestation',
    scope: 'packages/host',
  },
  {
    id: 'temp-warning-is-still-a-reading',
    why: '`warning` / `alarm` 表示值越过报警带，不表示读不到。踢出去 ⇒ 一台正从 300 K 降下来的机器（降温途中必然长期在警带里）对「现在几度」一路回答「读不到」，而那正是等降温唯一要看的数',
    file: `${K}/temperature.ts`,
    find: "const LIVE_STATUSES = ['ok', 'warning', 'alarm'] as const",
    replace: "const LIVE_STATUSES = ['ok'] as const",
    scope: 'packages/host',
  },
  {
    id: 'temp-unknown-real-is-not-placeholder',
    why: '`real` 三态：`false` 才是占位，`null` 是**不知道**。把不知道当占位 ⇒ 一台正常报着 77 K 的机器被判成「没装温度计」，而那条建议是「等下去永远等不到」',
    file: `${K}/temperature.ts`,
    find: '      reason: c.real === false ? NO_SENSOR : UNAVAILABLE,',
    replace: '      reason: c.real !== true ? NO_SENSOR : UNAVAILABLE,',
    scope: 'packages/host',
  },
  {
    id: 'temp-unknown-age-is-not-fresh',
    why: '年龄不明时 `freshness` 必须是 `unknown`。补个 0 ⇒ 「不知道多旧」变成「刚刚读的」，而等到温的那道闸会当场通过',
    file: `${K}/temperature.ts`,
    find: '  return r.ageS\n}',
    replace: '  return r.ageS ?? 0\n}',
    scope: 'packages/host',
  },
  {
    id: 'temp-ambiguous-is-not-a-pick',
    why: '名字对上两个通道 ⇒ 说清是哪个。悄悄挑一个 ⇒ 挑错的那半时间没人会发现，而磁体杜瓦的温度不等于样品台的温度',
    file: `${K}/temperature.ts`,
    find: '  if (subHits.length > 1) return { hit: null, why: AMBIGUOUS_CHANNEL }',
    replace: '  if (subHits.length > 1) return { hit: subHits[0] as TempChannel, why: null }',
    scope: 'packages/host',
  },
  {
    id: 'temp-stage-preference',
    why: '多个可读通道时**优先样品台**。改成取第一个 ⇒ 「现在几度」回的是磁体杜瓦的温度，而它与样品台可以差两个数量级',
    file: `${K}/temperature.ts`,
    find: '    if (STAGE_HINTS.some((h) => low.includes(h))) return c',
    replace: '    if (false && STAGE_HINTS.some((h) => low.includes(h))) return c',
    scope: 'packages/host',
  },
  {
    id: 'temp-channels-null-is-not-empty',
    why: '`channels()` 的 `null` = 问不到，`[]` = 确实没有。折成 `[]` ⇒ 一个没接上源的进程会让智能体得出「这台机器没温度计」，而那条结论的建议是「别再等了」',
    file: `${K}/temperature.ts`,
    find: '  if (src === null) return null',
    replace: '  if (src === null) return []',
    scope: 'packages/host',
  },
  {
    id: 'temp-zero-max-age-is-a-threshold',
    why: '`max_age_s = 0` 是合法阈值（声明里 min_value=0.0），意思是「一切都算旧」。用真假判它 ⇒ 最严的那一档静静退化成**不判**（D-ZERO-1 第五次）',
    file: `${SK}/l0/environment.ts`,
    find: "  return params['max_age_s'] != null",
    replace: "  return Boolean(params['max_age_s'])",
    scope: 'packages/host/stm-skills',
  },
  {
    id: 'temp-freshness-is-explicit-only',
    why: '不传阈值就**不判**陈旧，而不是拿一个默认阈值算一个结论 —— 那种结论看起来和真的一样。改成永远判 ⇒ 调用方以为自己看到的是自己的判据',
    file: `${SK}/l0/environment.ts`,
    find: '    if (givenMaxAge(params)) {',
    replace: '    if (givenMaxAge(params) || true) {',
    scope: 'packages/host/stm-skills',
  },
]
